/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--h-color-primary)",
          25: "var(--h-color-primary-25)",
          50: "var(--h-color-primary-50)",
          100: "var(--h-color-primary-100)",
          200: "var(--h-color-primary-200)",
          300: "var(--h-color-primary-300)",
          400: "var(--h-color-primary-400)",
          500: "var(--h-color-primary-500)",
          600: "var(--h-color-primary-600)",
          700: "var(--h-color-primary-700)",
          800: "var(--h-color-primary-800)",
          900: "var(--h-color-primary-900)",
        },
        brand: {
          DEFAULT: "var(--colors-brand-500)",
          50: "var(--colors-brand-50)",
          100: "var(--colors-brand-100)",
          200: "var(--colors-brand-200)",
          300: "var(--colors-brand-300)",
          35: "var(--colors-brand-35)",
          40: "var(--colors-brand-40)",
          42: "var(--colors-brand-42)",
          45: "var(--colors-brand-45)",
          400: "var(--colors-brand-400)",
          500: "var(--colors-brand-500)",
          600: "var(--colors-brand-600)",
          700: "var(--colors-brand-700)",
          800: "var(--colors-brand-800)",
          900: "var(--colors-brand-900)",
          950: "var(--colors-brand-950)",
        },
        blue: {
          100: "var(--colors-blue-100)",
          200: "var(--colors-blue-200)",
          300: "var(--colors-blue-300)",
          400: "var(--colors-blue-400)",
          50: "var(--colors-blue-50)",
          500: "var(--colors-blue-500)",
          600: "var(--colors-blue-600)",
          700: "var(--colors-blue-700)",
          800: "var(--colors-blue-800)",
          900: "var(--colors-blue-900)",
          950: "var(--colors-blue-950)",
        },
        coral: {
          50: "var(--colors-coral-50)",
          100: "var(--colors-coral-100)",
          200: "var(--colors-coral-200)",
          300: "var(--colors-coral-300)",
          400: "var(--colors-coral-400)",
          500: "var(--colors-coral-500)",
          600: "var(--colors-coral-600)",
          700: "var(--colors-coral-700)",
          800: "var(--colors-coral-800)",
          900: "var(--colors-coral-900)",
          950: "var(--colors-coral-950)",
        },
        green: {
          50: "var(--colors-green-50)",
          100: "var(--colors-green-100)",
          200: "var(--colors-green-200)",
          300: "var(--colors-green-300)",
          400: "var(--colors-green-400)",
          500: "var(--colors-green-500)",
          600: "var(--colors-green-600)",
          700: "var(--colors-green-700)",
          800: "var(--colors-green-800)",
          900: "var(--colors-green-900)",
          950: "var(--colors-green-950)",
        },
        purple: {
          50: "var(--colors-purple-50)",
          100: "var(--colors-purple-100)",
          200: "var(--colors-purple-200)",
          300: "var(--colors-purple-300)",
          400: "var(--colors-purple-400)",
          500: "var(--colors-purple-500)",
          600: "var(--colors-purple-600)",
          700: "var(--colors-purple-700)",
          800: "var(--colors-purple-800)",
          900: "var(--colors-purple-900)",
          950: "var(--colors-purple-950)",
        },
        yellow: {
          50: "var(--colors-yellow-50)",
          100: "var(--colors-yellow-100)",
          200: "var(--colors-yellow-200)",
          300: "var(--colors-yellow-300)",
          400: "var(--colors-yellow-400)",
          500: "var(--colors-yellow-500)",
          600: "var(--colors-yellow-600)",
          700: "var(--colors-yellow-700)",
          800: "var(--colors-yellow-800)",
          900: "var(--colors-yellow-900)",
          950: "var(--colors-yellow-950)",
        },
        "warn-orange": {
          100: "var(--colors-warn-orange-100)",
          200: "var(--colors-warn-orange-200)",
          300: "var(--colors-warn-orange-300)",
          400: "var(--colors-warn-orange-400)",
          50: "var(--colors-warn-orange-50)",
          500: "var(--colors-warn-orange-500)",
          600: "var(--colors-warn-orange-600)",
          700: "var(--colors-warn-orange-700)",
          800: "var(--colors-warn-orange-800)",
          900: "var(--colors-warn-orange-900)",
          950: "var(--colors-warn-orange-950)",
        },
        indigo: {
          50: "var(--colors-indigo-50)",
          100: "var(--colors-indigo-100)",
          200: "var(--colors-indigo-200)",
          300: "var(--colors-indigo-300)",
          400: "var(--colors-indigo-400)",
          500: "var(--colors-indigo-500)",
          600: "var(--colors-indigo-600)",
          700: "var(--colors-indigo-700)",
          800: "var(--colors-indigo-800)",
          900: "var(--colors-indigo-900)",
          950: "var(--colors-indigo-950)",
        },
        gray: {
          25: "var(--h-color-gray-25)",
          50: "var(--h-color-gray-50)",
          100: "var(--h-color-gray-100)",
          200: "var(--h-color-gray-200)",
          300: "var(--h-color-gray-300)",
          400: "var(--h-color-gray-400)",
          500: "var(--h-color-gray-500)",
          600: "var(--h-color-gray-600)",
          700: "var(--h-color-gray-700)",
          800: "var(--h-color-gray-800)",
          900: "var(--h-color-gray-900)",
        },
        "neutral-cool": {
          50: "var(--colors-neutral-cool-50)",
          100: "var(--colors-neutral-cool-100)",
          200: "var(--colors-neutral-cool-200)",
          300: "var(--colors-neutral-cool-300)",
          400: "var(--colors-neutral-cool-400)",
          500: "var(--colors-neutral-cool-500)",
          600: "var(--colors-neutral-cool-600)",
          700: "var(--colors-neutral-cool-700)",
          800: "var(--colors-neutral-cool-800)",
          900: "var(--colors-neutral-cool-900)",
        },
        "warn-orange": {
          50: "var(--colors-warn-orange-50)",
          100: "var(--colors-warn-orange-100)",
          200: "var(--colors-warn-orange-200)",
          300: "var(--colors-warn-orange-300)",
          400: "var(--colors-warn-orange-400)",
          500: "var(--colors-warn-orange-500)",
          600: "var(--colors-warn-orange-600)",
          700: "var(--colors-warn-orange-700)",
          800: "var(--colors-warn-orange-800)",
          900: "var(--colors-warn-orange-900)",
          950: "var(--colors-warn-orange-950)",
        },
        error: {
          DEFAULT: "var(--colors-error-red-400)",
          25: "var(--h-color-error-25)",
          50: "var(--h-color-error-50)",
          100: "var(--h-color-error-100)",
          200: "var(--h-color-error-200)",
          300: "var(--h-color-error-300)",
          400: "var(--h-color-error-400)",
          500: "var(--h-color-error-500)",
          600: "var(--h-color-error-600)",
          700: "var(--h-color-error-700)",
          800: "var(--h-color-error-800)",
          900: "var(--h-color-error-900)",
          stroke: "var(--colors-error-red-500)",
          fill: "var(--colors-error-red-50)",
        },
        "error-ds": {
          50: "var(--colors-error-red-50)",
          100: "var(--colors-error-red-100)",
          200: "var(--colors-error-red-200)",
          300: "var(--colors-error-red-300)",
          400: "var(--colors-error-red-400)",
          500: "var(--colors-error-red-500)",
          600: "var(--colors-error-red-600)",
          700: "var(--colors-error-red-700)",
          800: "var(--colors-error-red-800)",
          900: "var(--colors-error-red-900)",
          950: "var(--colors-error-red-950)",
        },
        warning: {
          25: "var(--h-color-warning-25)",
          50: "var(--h-color-warning-50)",
          100: "var(--h-color-warning-100)",
          200: "var(--h-color-warning-200)",
          300: "var(--h-color-warning-300)",
          400: "var(--h-color-warning-400)",
          500: "var(--h-color-warning-500)",
          600: "var(--h-color-warning-600)",
          700: "var(--h-color-warning-700)",
          800: "var(--h-color-warning-800)",
          900: "var(--h-color-warning-900)",
          stroke: "var(--colors-warn-orange-500)",
          fill: "var(--colors-warn-orange-50)",
        },
        success: {
          DEFAULT: "var(--colors-green-700)",
          25: "var(--h-color-success-25)",
          50: "var(--h-color-success-50)",
          100: "var(--h-color-success-100)",
          200: "var(--h-color-success-200)",
          300: "var(--h-color-success-300)",
          400: "var(--h-color-success-400)",
          500: "var(--h-color-success-500)",
          600: "var(--h-color-success-600)",
          700: "var(--h-color-success-700)",
          800: "var(--h-color-success-800)",
          900: "var(--h-color-success-900)",
          stroke: "var(--colors-emerald-500)",
          fill: "var(--colors-emerald-50)",
        },
        info: {
          25: "var(--h-color-info-25)",
          50: "var(--h-color-info-50)",
          100: "var(--h-color-info-100)",
          200: "var(--h-color-info-200)",
          300: "var(--h-color-info-300)",
          400: "var(--h-color-info-400)",
          500: "var(--h-color-info-500)",
          600: "var(--h-color-info-600)",
          700: "var(--h-color-info-700)",
          800: "var(--h-color-info-800)",
          900: "var(--h-color-info-900)",
          stroke: "var(--colors-blue-500)",
          fill: "var(--colors-blue-50)",
        },
        emerald: {
          100: "var(--colors-emerald-100)",
          200: "var(--colors-emerald-200)",
          300: "var(--colors-emerald-300)",
          400: "var(--colors-emerald-400)",
          500: "var(--colors-emerald-500)",
          600: "var(--colors-emerald-600)",
          700: "var(--colors-emerald-700)",
          800: "var(--colors-emerald-800)",
          900: "var(--colors-emerald-900)",
        },
        black: {
          0: "#000000",
          4: "var(--colors-neutral-cool-black-04)",
          8: "var(--colors-neutral-cool-black-08)",
          12: "var(--colors-neutral-cool-black-12)",
          16: "var(--colors-neutral-cool-black-16)",
          20: "var(--colors-neutral-cool-black-20)",
          30: "var(--colors-neutral-cool-black-30)",
          40: "var(--colors-neutral-cool-black-40)",
          50: "var(--colors-neutral-cool-black-50)",
          60: "var(--colors-neutral-cool-black-60)",
          70: "var(--colors-neutral-cool-black-70)",
          80: "var(--colors-neutral-cool-black-80)",
        },
        icon: {
          high: "var(--icon-high-emphasis)",
          "high-invert": "var(--icon-high-emphasis-invert)",
          information: "var(--icon-information)",
          mid: "var(--icon-mid-emphasis)",
          "mid-invert": "var(--icon-mid-emphasis-invert)",
          low: "var(--icon-low-emphasis)",
          "low-invert": "var(--icon-low-emphasis-invert)",
          success: "var(--icon-success)",
          error: "var(--icon-error)",
          warning: "var(--icon-warning)",
          action: "var(--icon-action)",
        },
        emphasis: {
          high: "var(--content-high-emphasis)",
          mid: "var(--content-mid-emphasis)",
          low: "var(--content-low-emphasis)",
        },
        content: {
          high: "var(--content-high-emphasis)",
          "high-inverse": "var(--content-high-emphasis-inverse)",
          information: "var(--content-information)",
          mid: "var(--content-mid-emphasis)",
          "mid-inverse": "var(--content-mid-emphasis-inverse)",
          low: "var(--content-low-emphasis)",
          "low-inverse": "var(--content-low-emphasis-inverse)",
          action: "var(--content-action)",
          error: "var(--content-error)",
          success: "var(--content-success)",
          warning: "var(--content-warning)",
        },
        stroke: {
          high: "var(--stroke-color-high-emphasis)",
          mid: "var(--stroke-color-mid-emphasis)",
          low: "var(--stroke-color-low-emphasis)",
          "black-04": "var(--stroke-color-black-04)",
          "black-08": "var(--stroke-color-black-08)",
          "black-12": "var(--stroke-color-black-12)",
          "cool-black-04": "var(--colors-neutral-cool-black-04)",
          "cool-black-08": "var(--colors-neutral-cool-black-08)",
          "cool-black-12": "var(--colors-neutral-cool-black-12)",
          dark: "var(--stroke-color-dark)",
          positive: "var(--stroke-color-positive)",
          "black-04": "var(--stroke-color-black-04)",
          "color-orange-subtle-light": "var(--stroke-color-orange-light)",
          "brand-default": "var(--stroke-color-brand-default)",
          "brand-light": "var(--stroke-color-brand-light)",
        },
        pastels: {
          blue: {
            50: "var(--colors-pastels-blue-50)",
            100: "var(--colors-pastels-blue-100)",
            150: "var(--colors-pastels-blue-150)",
            200: "var(--colors-pastels-blue-200)",
            250: "var(--colors-pastels-blue-250)",
            400: "var(--colors-pastels-blue-400)",
          },
          brand: {
            50: "var(--colors-pastels-brand-50)",
            100: "var(--colors-pastels-brand-100)",
            150: "var(--colors-pastels-brand-150)",
            200: "var(--colors-pastels-brand-200)",
            250: "var(--colors-pastels-brand-250)",
            400: "var(--colors-pastels-brand-400)",
          },
          brown: {
            50: "var(--colors-pastels-brown-50)",
            100: "var(--colors-pastels-brown-100)",
            150: "var(--colors-pastels-brown-150)",
            200: "var(--colors-pastels-brown-200)",
            250: "var(--colors-pastels-brown-250)",
            400: "var(--colors-pastels-brown-400)",
          },
          coral: {
            50: "var(--colors-pastels-coral-50)",
            100: "var(--colors-pastels-coral-100)",
            150: "var(--colors-pastels-coral-150)",
            200: "var(--colors-pastels-coral-200)",
            250: "var(--colors-pastels-coral-250)",
            400: "var(--colors-pastels-coral-400)",
          },
          cyan: {
            50: "var(--colors-pastels-cyan-50)",
            100: "var(--colors-pastels-cyan-100)",
            150: "var(--colors-pastels-cyan-150)",
            200: "var(--colors-pastels-cyan-200)",
            250: "var(--colors-pastels-cyan-250)",
            400: "var(--colors-pastels-cyan-400)",
          },
          emerald: {
            50: "var(--colors-pastels-emerald-50)",
            100: "var(--colors-pastels-emerald-100)",
            150: "var(--colors-pastels-emerald-150)",
            200: "var(--colors-pastels-emerald-200)",
            250: "var(--colors-pastels-emerald-250)",
            400: "var(--colors-pastels-emerald-400)",
          },
          errorRed: {
            50: "var(--colors-pastels-error-red-50)",
            100: "var(--colors-pastels-error-red-100)",
            150: "var(--colors-pastels-error-red-150)",
            200: "var(--colors-pastels-error-red-200)",
            250: "var(--colors-pastels-error-red-250)",
            400: "var(--colors-pastels-error-red-400)",
          },
          green: {
            50: "var(--colors-pastels-green-50)",
            100: "var(--colors-pastels-green-100)",
            150: "var(--colors-pastels-green-150)",
            200: "var(--colors-pastels-green-200)",
            250: "var(--colors-pastels-green-250)",
            400: "var(--colors-pastels-green-400)",
          },
          indigo: {
            50: "var(--colors-pastels-indigo-50)",
            100: "var(--colors-pastels-indigo-100)",
            150: "var(--colors-pastels-indigo-150)",
            200: "var(--colors-pastels-indigo-200)",
            250: "var(--colors-pastels-indigo-250)",
            400: "var(--colors-pastels-indigo-400)",
          },
          magenta: {
            50: "var(--colors-pastels-magenta-50)",
            100: "var(--colors-pastels-magenta-100)",
            150: "var(--colors-pastels-magenta-150)",
            200: "var(--colors-pastels-magenta-200)",
            250: "var(--colors-pastels-magenta-250)",
            400: "var(--colors-pastels-magenta-400)",
          },
          neutralGray: {
            50: "var(--colors-pastels-neutral-gray-50)",
            100: "var(--colors-pastels-neutral-gray-100)",
            150: "var(--colors-pastels-neutral-gray-150)",
            200: "var(--colors-pastels-neutral-gray-200)",
            250: "var(--colors-pastels-neutral-gray-250)",
            400: "var(--colors-pastels-neutral-gray-400)",
          },
          pink: {
            50: "var(--colors-pastels-pink-50)",
            100: "var(--colors-pastels-pink-100)",
            150: "var(--colors-pastels-pink-150)",
            200: "var(--colors-pastels-pink-200)",
            250: "var(--colors-pastels-pink-250)",
            400: "var(--colors-pastels-pink-400)",
          },
          purple: {
            50: "var(--colors-pastels-purple-50)",
            100: "var(--colors-pastels-purple-100)",
            150: "var(--colors-pastels-purple-150)",
            200: "var(--colors-pastels-purple-200)",
            250: "var(--colors-pastels-purple-250)",
            400: "var(--colors-pastels-purple-400)",
          },
          teal: {
            50: "var(--colors-pastels-teal-50)",
            100: "var(--colors-pastels-teal-100)",
            150: "var(--colors-pastels-teal-150)",
            200: "var(--colors-pastels-teal-200)",
            250: "var(--colors-pastels-teal-250)",
            400: "var(--colors-pastels-teal-400)",
          },
          warnOrange: {
            50: "var(--colors-pastels-warn-orange-50)",
            100: "var(--colors-pastels-warn-orange-100)",
            150: "var(--colors-pastels-warn-orange-150)",
            200: "var(--colors-pastels-warn-orange-200)",
            250: "var(--colors-pastels-warn-orange-250)",
            400: "var(--colors-pastels-warn-orange-400)",
          },
          yellow: {
            50: "var(--colors-pastels-yellow-50)",
            100: "var(--colors-pastels-yellow-100)",
            150: "var(--colors-pastels-yellow-150)",
            200: "var(--colors-pastels-yellow-200)",
            250: "var(--colors-pastels-yellow-250)",
            400: "var(--colors-pastels-yellow-400)",
          },
        },
        surface: {
          success: "var(--surface-success)",
          primary: "var(--surface-primary)",
          danger: " var(--surface-danger)",
          "danger-light": "var(--surface-danger-light)",
          "danger-subtle": "var(--surface-danger-subtle)",
          hover: "var(--surface-hover)",
          secondary: "var(--surface-secondary)",
          "secondary-light": "var(--surface-secondary-light)",
          page: "var(--surface-page)",
          "brand-surface-light": "var(--surface-brand-surface-light)",
          "brand-subtle": "var(--surface-brand-subtle)",
          "brand-default": "var(--surface-brand-default)",
          "brand-strong": "var(--surface-brand-strong)",
          "success-subtle": "var(--surface-success-subtle)",
          "on-notification-badge": "var(--surface-on-notification-badge)",
          "notification-badge": "var(--surface-notification-badge)",
          action: "var(--surface-action)",
          "action-hover": "var(--surface-action-hover)",
          "orange-subtle": "var(--surface-orange-subtle)",
          "brand-subtle": "var(--surface-brand-subtle)",
          info: "var(--surface-info)",

          pastel: {
            /* ─── shade maps ───────────────────────────────────── */
            blue: {
              50: "var(--colors-pastels-blue-50)",
              100: "var(--colors-pastels-blue-100)",
              150: "var(--colors-pastels-blue-150)",
              200: "var(--colors-pastels-blue-200)",
              250: "var(--colors-pastels-blue-250)",
              400: "var(--colors-pastels-blue-400)",
            },
            brand: {
              50: "var(--colors-pastels-brand-50)",
              100: "var(--colors-pastels-brand-100)",
              150: "var(--colors-pastels-brand-150)",
              200: "var(--colors-pastels-brand-200)",
              250: "var(--colors-pastels-brand-250)",
              400: "var(--colors-pastels-brand-400)",
            },
            foreground: {
              brand: "var(--surface-pastel-foreground-brand)",
              brandRich: "var(--surface-pastel-foreground-brand-rich)",
              blue: "var(--surface-pastel-foreground-blue)",
              blueRich: "var(--surface-pastel-foreground-blue-rich)",
              green: "var(--surface-pastel-foreground-green)",
              greenRich: "var(--surface-pastel-foreground-green-rich)",
              indigo: "var(--surface-pastel-foreground-indigo)",
              indigoRich: "var(--surface-pastel-foreground-indigo)",
              orange: "var(--surface-pastel-foreground-orange)",
              purple: "var(--surface-pastel-foreground-purple)",
              red: "var(--surface-pastel-foreground-red)",
              redRich: "var(--surface-pastel-foreground-red-rich)",
            },
            brown: {
              50: "var(--colors-pastels-brown-50)",
              100: "var(--colors-pastels-brown-100)",
              150: "var(--colors-pastels-brown-150)",
              200: "var(--colors-pastels-brown-200)",
              250: "var(--colors-pastels-brown-250)",
              400: "var(--colors-pastels-brown-400)",
            },
            coral: {
              50: "var(--colors-pastels-coral-50)",
              100: "var(--colors-pastels-coral-100)",
              150: "var(--colors-pastels-coral-150)",
              200: "var(--colors-pastels-coral-200)",
              250: "var(--colors-pastels-coral-250)",
              400: "var(--colors-pastels-coral-400)",
            },
            cyan: {
              50: "var(--colors-pastels-cyan-50)",
              100: "var(--colors-pastels-cyan-100)",
              150: "var(--colors-pastels-cyan-150)",
              200: "var(--colors-pastels-cyan-200)",
              250: "var(--colors-pastels-cyan-250)",
              400: "var(--colors-pastels-cyan-400)",
            },
            emerald: {
              50: "var(--colors-pastels-emerald-50)",
              100: "var(--colors-pastels-emerald-100)",
              150: "var(--colors-pastels-emerald-150)",
              200: "var(--colors-pastels-emerald-200)",
              250: "var(--colors-pastels-emerald-250)",
              400: "var(--colors-pastels-emerald-400)",
            },
            errorRed: {
              50: "var(--colors-pastels-error-red-50)",
              100: "var(--colors-pastels-error-red-100)",
              150: "var(--colors-pastels-error-red-150)",
              200: "var(--colors-pastels-error-red-200)",
              250: "var(--colors-pastels-error-red-250)",
              400: "var(--colors-pastels-error-red-400)",
            },
            green: {
              50: "var(--colors-pastels-green-50)",
              100: "var(--colors-pastels-green-100)",
              150: "var(--colors-pastels-green-150)",
              200: "var(--colors-pastels-green-200)",
              250: "var(--colors-pastels-green-250)",
              400: "var(--colors-pastels-green-400)",
            },
            indigo: {
              50: "var(--colors-pastels-indigo-50)",
              100: "var(--colors-pastels-indigo-100)",
              150: "var(--colors-pastels-indigo-150)",
              200: "var(--colors-pastels-indigo-200)",
              250: "var(--colors-pastels-indigo-250)",
              400: "var(--colors-pastels-indigo-400)",
            },
            magenta: {
              50: "var(--colors-pastels-magenta-50)",
              100: "var(--colors-pastels-magenta-100)",
              150: "var(--colors-pastels-magenta-150)",
              200: "var(--colors-pastels-magenta-200)",
              250: "var(--colors-pastels-magenta-250)",
              400: "var(--colors-pastels-magenta-400)",
            },
            gray: {
              50: "var(--colors-pastels-neutral-gray-50)",
              100: "var(--colors-pastels-neutral-gray-100)",
              150: "var(--colors-pastels-neutral-gray-150)",
              200: "var(--colors-pastels-neutral-gray-200)",
              250: "var(--colors-pastels-neutral-gray-250)",
              400: "var(--colors-pastels-neutral-gray-400)",
            },
            pink: {
              50: "var(--colors-pastels-pink-50)",
              100: "var(--colors-pastels-pink-100)",
              150: "var(--colors-pastels-pink-150)",
              200: "var(--colors-pastels-pink-200)",
              250: "var(--colors-pastels-pink-250)",
              400: "var(--colors-pastels-pink-400)",
            },
            purple: {
              50: "var(--colors-pastels-purple-50)",
              100: "var(--colors-pastels-purple-100)",
              150: "var(--colors-pastels-purple-150)",
              200: "var(--colors-pastels-purple-200)",
              250: "var(--colors-pastels-purple-250)",
              400: "var(--colors-pastels-purple-400)",
            },
            teal: {
              50: "var(--colors-pastels-teal-50)",
              100: "var(--colors-pastels-teal-100)",
              150: "var(--colors-pastels-teal-150)",
              200: "var(--colors-pastels-teal-200)",
              250: "var(--colors-pastels-teal-250)",
              400: "var(--colors-pastels-teal-400)",
            },
            warnOrange: {
              50: "var(--colors-pastels-warn-orange-50)",
              100: "var(--colors-pastels-warn-orange-100)",
              150: "var(--colors-pastels-warn-orange-150)",
              200: "var(--colors-pastels-warn-orange-200)",
              250: "var(--colors-pastels-warn-orange-250)",
              400: "var(--colors-pastels-warn-orange-400)",
            },
            yellow: {
              50: "var(--colors-pastels-yellow-50)",
              100: "var(--colors-pastels-yellow-100)",
              150: "var(--colors-pastels-yellow-150)",
              200: "var(--colors-pastels-yellow-200)",
              250: "var(--colors-pastels-yellow-250)",
              400: "var(--colors-pastels-yellow-400)",
            },
            background: {
              blue: "var(--surface-pastel-background-blue)",
              blueRich: "var(--surface-pastel-background-blue-rich)",
              "blue-rich": "var(--surface-pastel-background-blue-rich)",
              brand: "var(--surface-pastel-background-brand)",
              brandRich: "var(--surface-pastel-background-brand-rich)",
              brown: "var(--surface-pastel-background-brown)",
              brownRich: "var(--surface-pastel-background-brown-rich)",
              coral: "var(--surface-pastel-background-coral)",
              cyan: "var(--surface-pastel-background-cyan)",
              emerald: "var(--surface-pastel-background-emerald)",
              emeraldRich: "var(--surface-pastel-background-emerald-rich)",
              gray: "var(--surface-pastel-background-gray)",
              grayRich: "var(--surface-pastel-background-gray-rich)",
              graySoft: "var(--surface-pastel-background-gray-soft)",
              green: "var(--surface-pastel-background-green)",
              greenRich: "var(--surface-pastel-background-green-rich)",
              indigo: "var(--surface-pastel-background-indigo)",
              indigoRich: "var(--surface-pastel-background-indigo-rich)",
              magenta: "var(--surface-pastel-background-magenta)",
              magentaRich: "var(--surface-pastel-background-magenta-rich)",
              orange: "var(--surface-pastel-background-orange)",
              orangeRich: "var(--surface-pastel-background-orange-rich)",
              pink: "var(--surface-pastel-background-pink)",
              pinkRich: "var(--surface-pastel-background-pink-rich)",
              pinkSoft: "var(--surface-pastel-background-pink-soft)",
              purple: "var(--surface-pastel-background-purple)",
              purpleRich: "var(--surface-pastel-background-purple-rich)",
              red: "var(--surface-pastel-background-red)",
              redRich: "var(--surface-pastel-background-red-rich)",
              teal: "var(--surface-pastel-background-teal)",
              tealRich: "var(--surface-pastel-background-teal-rich)",
              yellow: "var(--surface-pastel-background-yellow)",
            },
          },
          "contrast-over": {
            "color-lv0": "var(--surface-contrast-over-color-lv0)",
            "color-lvl1": "var(--surface-contrast-over-color-lvl1)",
            "color-lvl2": "var(--surface-contrast-over-color-lvl2)",
            "color-lvl3": "var(--surface-contrast-over-color-lvl3)",
            "color-lvl4": "var(--surface-contrast-over-color-lvl4)",
          },
        },
        feedback: {
          "stroke-danger": "var(--f-stroke-danger)",
          "stroke-exciting": "var(--f-stroke-exciting)",
          "stroke-highlight-positive": "var(--f-stroke-highlight-positive)",
          "stroke-info": "var(--f-stroke-info)",
          "stroke-positive": "var(--f-stroke-positive)",
          "stroke-warn": "var(--f-stroke-warn)",
          "surface-danger": "var(--f-surface-danger)",
          "surface-highlight-positive": "var(--f-surface-highlight-positive)",
          "surface-info": "var(--f-surface-info)",
          "surface-positive": "var(--f-surface-positive)",
          "surface-warn": "var(--f-surface-warn)",
          primary: "var(--surface-primary)",
          secondary: "var(--surface-secondary)",
          success: "var(--surface-success)",
          warning: "var(--surface-warning)",
          hover: "var(--colors-neutral-cool-black-12)",
        },
        // Custom DS Icon Colors - exact colors from original SVGs
        "ds-icon": {
          exam: "#B85BEA", // ds-exam original color
          assignment: "#62BA0A", // ds-assignment original color
          attachment: "#EC6955", // ds-attachment original color
          video: "#7883EA", // ds-video original color
          quiz: "#E47097", // ds-quiz original color
          image: "#6CCBFA", // ds-image original color
        },
      },
      boxShadow: {
        xs: "0px 1px 2px 0px rgba(16, 24, 40, 0.05)",
        lg: "0px 4px 6px -2px rgba(16, 24, 40, 0.03), 0px 12px 16px -4px rgba(16, 24, 40, 0.08)",
      },
      scale: {
        103: "1.03",
      },
      fontSize: {
        "ds-xs": "var(--font-size-xs)",
        "ds-sm": "var(--font-size-sm)",
        "ds-base": "var(--font-size-base)",
        "ds-lg": "var(--font-size-lg)",
        "ds-xl": "var(--font-size-xl)",
        "ds-2xl": "var(--font-size-2xl)",
        "ds-3xl": "var(--font-size-3xl)",
        "ds-4xl": "var(--font-size-4xl)",
        linkLg: [
          "var(--h-typography-utility-link-lg-font-size)",
          "var(--h-typography-utility-link-lg-line-height)",
        ],
      },
      spacing: {
        128: "32rem",
        "ds-xs": "var(--ds-spacing-xs)",
        "ds-sm": "var(--ds-spacing-sm)",
        "ds-md": "var(--ds-spacing-md)",
        "ds-lg": "var(--ds-spacing-lg)",
        "ds-xl": "var(--ds-spacing-xl)",
        "ds-2xl": "var(--ds-spacing-2xl)",
      },
      gap: {
        "ds-xs": "var(--ds-gaps-xs)",
        "ds-sm": "var(--ds-gaps-sm)",
        "ds-md": "var(--ds-gaps-md)",
        "ds-lg": "var(--ds-gaps-lg)",
        "ds-xl": "var(--ds-gaps-xl)",
        "ds-2xl": "var(--ds-gaps-2xl)",
        "ds-3xl": "var(--ds-gaps-3xl)",
      },
      borderRadius: {
        "ds-xs": "var(--ds-corner-radius-xs)",
        "ds-sm": "var(--ds-corner-radius-sm)",
        "ds-md": "var(--ds-corner-radius-md)",
        "ds-lg": "var(--ds-corner-radius-lg)",
        "ds-xl": "var(--ds-corner-radius-xl)",
        "ds-2xl": "var(--ds-corner-radius-2xl)",
        "ds-full": "9999px",
      },
      screens: {
        laptopL: "1440px",
        "3xl": "1920px", // Extra wide screens for 4-column layouts
        // These will allow us to use classes like: mobile-only:hidden, tablet-only:block, desktop-min:flex
        "mobile-only": { max: "599px" }, // Mobile only (< 600px)
        "tablet-min": { min: "600px" }, // Tablet and up (600px+)
        "tablet-only": { min: "600px", max: "840px" }, // Tablet only (600px - 840px)
        "desktop-min": { min: "841px" }, // Desktop and up (841px+)
      },
      animation: {
        progress: "progress 1s infinite linear",
      },
      keyframes: {
        progress: {
          "0%": { transform: " translateX(0) scaleX(0)" },
          "40%": { transform: "translateX(0) scaleX(0.4)" },
          "100%": { transform: "translateX(100%) scaleX(0.5)" },
        },
      },
      transformOrigin: {
        "left-right": "0% 50%",
      },
    },
  },
  plugins: [
    plugin(({ addVariant }) => {
      addVariant("personnel", '&:where([data-role="personnel"] *)');
      addVariant("student", '&:where([data-role="student"] *)');
    }),
    require("@tailwindcss/forms"),
  ],
};
