import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  // People & Users
  faUser,
  faUsers,
  faUserGroup,
  faUserPlus,
  faUserCheck,
  faUserGraduate,
  faChild,
  faPeopleGroup,
  faPersonChalkboard,
  faUserTie,
  faUserGear,
  faUserPen,
  faUserClock,
  faUserXmark,
  faUserMinus,
  faIdCard,
  faIdBadge,
  faAddressCard,
  faChildReaching,

  // Communication & Messaging
  faEnvelope,
  faEnvelopeOpen,
  faEnvelopeCircleCheck,
  faPhone,
  faPhoneVolume,
  faMessage,
  faComments,
  faComment,
  faCommentDots,
  faBell,
  faBellSlash,
  faPaperPlane,
  faAt,
  faInbox,
  faReply,

  // Alerts & Info
  faCircleInfo,
  faCircleQuestion,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleCheck,
  faCircleXmark,
  faLightbulb,
  faBullhorn,
  faBan,
  faCircleMinus,

  // Education & Learning
  faGraduationCap,
  faBook,
  faBookOpen,
  faBookOpenReader,
  faBooks,
  faChalkboardUser,
  faChalkboard,
  faPen,
  faPencil,
  faSchool,
  faSchoolFlag,
  faClipboard,
  faClipboardList,
  faClipboardCheck,
  faClipboardQuestion,
  faBookmark,
  faAward,
  faScroll,
  faRuler,
  faCalculator,
  faFlask,
  faAtom,
  faDna,
  faLanguage,
  faSpellCheck,
  faListCheck,
  faSquareCheck,
  faBackpack,
  faAppleWhole,

  // Tests & Assessments
  faFileCircleQuestion,
  faFileCircleCheck,
  faFileCircleXmark,
  faListOl,
  faBallotCheck,
  faSquarePollVertical,
  faSquarePollHorizontal,
  faPercent,
  faRankingStar,

  // Files & Documents
  faFile,
  faFileLines,
  faFileContract,
  faFileCertificate,
  faFileSignature,
  faFileInvoice,
  faFileInvoiceDollar,
  faFolder,
  faFolderOpen,
  faFolderTree,
  faPaperclip,
  faFileExport,
  faFileImport,
  faFilePdf,
  faFileWord,
  faFileExcel,
  faFilePowerpoint,
  faFileImage,
  faFileAudio,
  faFileVideo,
  faFileZipper,
  faFilePlus,
  faFileMinus,
  faFileArrowUp,
  faFileArrowDown,

  // Time & Calendar
  faCalendar,
  faCalendarDays,
  faCalendarCheck,
  faCalendarXmark,
  faCalendarPlus,
  faCalendarMinus,
  faCalendarClock,
  faCalendarWeek,
  faClock,
  faClockRotateLeft,
  faHourglass,
  faHourglassHalf,
  faStopwatch,
  faAlarmClock,
  faTimer,

  // Feedback & Rating
  faStar,
  faStarHalf,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faFlag,
  faFlagCheckered,
  faTrophy,
  faTrophyStar,
  faMedal,
  faCrown,
  faHandshake,
  faHandsClapping,

  // Settings & Config
  faGear,
  faGears,
  faSliders,
  faWrench,
  faScrewdriverWrench,
  faToggleOn,
  faToggleOff,
  faCircleHalfStroke,

  // Security & Access
  faLock,
  faLockOpen,
  faLockKeyhole,
  faUnlockKeyhole,
  faKey,
  faShield,
  faShieldHalved,
  faShieldCheck,
  faUserShield,
  faFingerprint,
  faEye,
  faEyeSlash,
  faUserLock,

  // Places & Buildings
  faHouse,
  faBuilding,
  faBuildingColumns,
  faHospital,
  faStore,
  faWarehouse,
  faSchoolCircleCheck,
  faLocationDot,
  faMapLocationDot,
  faMap,
  faDoorOpen,
  faDoorClosed,
  faCity,

  // Finance & Payment
  faDollarSign,
  faMoneyBill,
  faMoneyBillWave,
  faMoneyBills,
  faMoneyCheck,
  faMoneyCheckDollar,
  faCreditCard,
  faWallet,
  faReceipt,
  faCoins,
  faSackDollar,
  faHandHoldingDollar,
  faScaleBalanced,
  faCircleDollar,
  faMoneyBillTransfer,
  faBadgeCheck,

  // Charts & Analytics
  faChartLine,
  faChartLineUp,
  faChartLineDown,
  faChartBar,
  faChartPie,
  faChartMixed,
  faChartSimple,
  faPresentationScreen,
  faGauge,
  faGaugeHigh,

  // Media & Content
  faCamera,
  faImage,
  faImages,
  faVideo,
  faMicrophone,
  faMicrophoneSlash,
  faHeadphones,
  faDisplay,
  faDesktop,
  faLaptop,
  faMobile,
  faTablet,
  faScreenUsers,
  faWebcam,
  faPhotoFilm,

  // Transportation
  faBus,
  faBusSchool,
  faCar,
  faRoute,
  faRoad,
  faLocationCrosshairs,
  faCompass,

  // Maintenance & Environment
  faBroom,
  faSprayCanSparkles,
  faTrashCan,
  faRecycle,
  faLeaf,
  faTree,
  faSeedling,
  faDroplet,
  faFan,
  faTemperatureHalf,
  faPlug,
  faToolbox,
  faHammer,

  // Food & Canteen
  faUtensils,
  faBowlFood,
  faMugHot,
  faGlassWater,
  faCookie,
  faCarrot,

  // Clothing & Uniform
  faShirt,
  faVest,
  faShoePrints,
  faSocks,

  // Help & Support
  faLifeRing,
  faHeadset,
  faHandshakeAngle,
  faHandHoldingHeart,
  faCertificate,

  // Accessibility
  faUniversalAccess,
  faWheelchair,
  faEarListen,
  faEarDeaf,
  faHandsAslInterpreting,
  faBraille,

  // Structure & Organization
  faSitemap,
  faDiagramProject,
  faListTree,
  faLayerGroup,
  faObjectGroup,
  faTableCells,
  faTableList,
  faGrid,

  // Roles & Permissions
  faUserTag,
  faUsersBetweenLines,
  faUsersRectangle,
  faUserSecret,
  faBookOpenCover,
  faBoxArchive,
  faUsersGear,

  // Announcements & Notifications
  faNewspaper,
  faRss,
  faTowerBroadcast,
  faSatelliteDish,

  // Search & Filter
  faMagnifyingGlass,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faFilter,
  faSort,

  // Actions
  faPlus,
  faMinus,
  faCheck,
  faXmark,
  faPenToSquare,
  faTrash,
  faDownload,
  faUpload,
  faShare,
  faShareNodes,
  faPrint,
  faCopy,
  faLink,
  faLinkSlash,
  faRotate,
  faArrowsRotate,
  faRightFromBracket,
  faRightToBracket,
  faExpand,
  faCompress,
} from '@fortawesome/pro-regular-svg-icons';

export interface IconOption {
  name: string;
  icon: IconDefinition;
  searchTerms: string[];
}

export const ICON_CHOOSER_OPTIONS: IconOption[] = [
  // ===== PEOPLE & USERS =====
  {
    name: 'fa-user',
    icon: faUser,
    searchTerms: [
      'user',
      'person',
      'profile',
      'account',
      'member',
      'individual',
      'مستخدم',
      'شخص',
      'حساب',
      'عضو',
      'فرد',
    ],
  },
  {
    name: 'fa-users',
    icon: faUsers,
    searchTerms: [
      'users',
      'people',
      'group',
      'team',
      'members',
      'community',
      'مستخدمين',
      'أشخاص',
      'مجموعة',
      'فريق',
      'أعضاء',
      'مجتمع',
    ],
  },
  {
    name: 'fa-user-group',
    icon: faUserGroup,
    searchTerms: [
      'user group',
      'team',
      'group',
      'people',
      'members',
      'مجموعة مستخدمين',
      'فريق',
      'مجموعة',
      'أشخاص',
      'أعضاء',
    ],
  },
  {
    name: 'fa-user-plus',
    icon: faUserPlus,
    searchTerms: [
      'add user',
      'new user',
      'register',
      'signup',
      'join',
      'إضافة مستخدم',
      'مستخدم جديد',
      'تسجيل',
      'انضمام',
    ],
  },
  {
    name: 'fa-user-check',
    icon: faUserCheck,
    searchTerms: [
      'verified user',
      'approved',
      'confirmed',
      'valid',
      'active',
      'مستخدم موثق',
      'موافق عليه',
      'مؤكد',
      'نشط',
    ],
  },
  {
    name: 'fa-user-graduate',
    icon: faUserGraduate,
    searchTerms: [
      'graduate',
      'student',
      'alumni',
      'scholar',
      'education',
      'خريج',
      'طالب',
      'خريجين',
      'باحث',
      'تعليم',
      'متخرج',
    ],
  },
  {
    name: 'fa-child',
    icon: faChild,
    searchTerms: [
      'child',
      'kid',
      'student',
      'young',
      'minor',
      'طفل',
      'صغير',
      'طالب',
      'قاصر',
      'ولد',
      'بنت',
    ],
  },
  {
    name: 'fa-child-reaching',
    icon: faChildReaching,
    searchTerms: [
      'child reaching',
      'kid playing',
      'active child',
      'طفل يلعب',
      'طفل نشيط',
      'لعب',
    ],
  },
  {
    name: 'fa-people-group',
    icon: faPeopleGroup,
    searchTerms: [
      'people group',
      'crowd',
      'assembly',
      'gathering',
      'community',
      'مجموعة أشخاص',
      'حشد',
      'تجمع',
      'مجتمع',
    ],
  },
  {
    name: 'fa-person-chalkboard',
    icon: faPersonChalkboard,
    searchTerms: [
      'teacher',
      'instructor',
      'presenter',
      'lecturer',
      'professor',
      'trainer',
      'معلم',
      'مدرس',
      'محاضر',
      'أستاذ',
      'مدرب',
    ],
  },
  {
    name: 'fa-user-tie',
    icon: faUserTie,
    searchTerms: [
      'professional',
      'business',
      'executive',
      'manager',
      'admin',
      'official',
      'محترف',
      'رجل أعمال',
      'مدير',
      'إداري',
      'رسمي',
    ],
  },
  {
    name: 'fa-user-gear',
    icon: faUserGear,
    searchTerms: [
      'user settings',
      'admin',
      'configuration',
      'preferences',
      'إعدادات المستخدم',
      'مشرف',
      'تكوين',
      'تفضيلات',
    ],
  },
  {
    name: 'fa-user-pen',
    icon: faUserPen,
    searchTerms: [
      'edit user',
      'modify profile',
      'update user',
      'تعديل مستخدم',
      'تحديث الملف الشخصي',
    ],
  },
  {
    name: 'fa-user-clock',
    icon: faUserClock,
    searchTerms: [
      'user schedule',
      'attendance',
      'time',
      'waiting',
      'جدول المستخدم',
      'حضور',
      'وقت',
      'انتظار',
    ],
  },
  {
    name: 'fa-user-xmark',
    icon: faUserXmark,
    searchTerms: [
      'remove user',
      'delete user',
      'cancel',
      'block',
      'حذف مستخدم',
      'إزالة مستخدم',
      'حظر',
      'إلغاء',
    ],
  },
  {
    name: 'fa-user-minus',
    icon: faUserMinus,
    searchTerms: [
      'remove user',
      'delete',
      'subtract',
      'إزالة مستخدم',
      'حذف',
      'طرح',
    ],
  },
  {
    name: 'fa-id-card',
    icon: faIdCard,
    searchTerms: [
      'id card',
      'identification',
      'badge',
      'license',
      'permit',
      'بطاقة هوية',
      'تعريف',
      'شارة',
      'رخصة',
      'تصريح',
    ],
  },
  {
    name: 'fa-id-badge',
    icon: faIdBadge,
    searchTerms: [
      'id badge',
      'employee badge',
      'name tag',
      'شارة هوية',
      'شارة موظف',
      'بطاقة اسم',
    ],
  },
  {
    name: 'fa-address-card',
    icon: faAddressCard,
    searchTerms: [
      'address card',
      'contact',
      'vcard',
      'profile card',
      'بطاقة عنوان',
      'اتصال',
      'بطاقة ملف شخصي',
    ],
  },
  {
    name: 'fa-users-gear',
    icon: faUsersGear,
    searchTerms: [
      'users settings',
      'team admin',
      'group config',
      'إعدادات المستخدمين',
      'إدارة الفريق',
      'تكوين المجموعة',
    ],
  },

  // ===== COMMUNICATION & MESSAGING =====
  {
    name: 'fa-envelope',
    icon: faEnvelope,
    searchTerms: [
      'email',
      'mail',
      'message',
      'letter',
      'inbox',
      'بريد إلكتروني',
      'رسالة',
      'بريد',
      'مراسلة',
      'ايميل',
    ],
  },
  {
    name: 'fa-envelope-open',
    icon: faEnvelopeOpen,
    searchTerms: [
      'open email',
      'read mail',
      'opened letter',
      'بريد مفتوح',
      'رسالة مقروءة',
    ],
  },
  {
    name: 'fa-envelope-circle-check',
    icon: faEnvelopeCircleCheck,
    searchTerms: [
      'email verified',
      'mail confirmed',
      'sent successfully',
      'بريد موثق',
      'تأكيد الإرسال',
    ],
  },
  {
    name: 'fa-phone',
    icon: faPhone,
    searchTerms: [
      'phone',
      'call',
      'telephone',
      'contact',
      'mobile',
      'هاتف',
      'اتصال',
      'تليفون',
      'موبايل',
      'جوال',
    ],
  },
  {
    name: 'fa-phone-volume',
    icon: faPhoneVolume,
    searchTerms: [
      'phone ringing',
      'incoming call',
      'loud',
      'هاتف يرن',
      'مكالمة واردة',
      'صوت',
    ],
  },
  {
    name: 'fa-message',
    icon: faMessage,
    searchTerms: [
      'message',
      'chat',
      'sms',
      'text',
      'conversation',
      'رسالة',
      'محادثة',
      'دردشة',
      'نص',
      'رسالة نصية',
    ],
  },
  {
    name: 'fa-comments',
    icon: faComments,
    searchTerms: [
      'comments',
      'chat',
      'discussion',
      'conversation',
      'forum',
      'تعليقات',
      'محادثة',
      'نقاش',
      'منتدى',
    ],
  },
  {
    name: 'fa-comment',
    icon: faComment,
    searchTerms: [
      'comment',
      'chat bubble',
      'message',
      'تعليق',
      'فقاعة محادثة',
      'رسالة',
    ],
  },
  {
    name: 'fa-comment-dots',
    icon: faCommentDots,
    searchTerms: [
      'typing',
      'thinking',
      'waiting',
      'dots',
      'جاري الكتابة',
      'تفكير',
      'انتظار',
      'نقاط',
    ],
  },
  {
    name: 'fa-bell',
    icon: faBell,
    searchTerms: [
      'bell',
      'notification',
      'alert',
      'reminder',
      'alarm',
      'جرس',
      'إشعار',
      'تنبيه',
      'تذكير',
      'منبه',
    ],
  },
  {
    name: 'fa-bell-slash',
    icon: faBellSlash,
    searchTerms: [
      'bell off',
      'mute',
      'silent',
      'no notifications',
      'جرس مغلق',
      'صامت',
      'كتم',
      'بدون إشعارات',
    ],
  },
  {
    name: 'fa-paper-plane',
    icon: faPaperPlane,
    searchTerms: [
      'send',
      'submit',
      'paper plane',
      'deliver',
      'إرسال',
      'تقديم',
      'طائرة ورقية',
      'توصيل',
    ],
  },
  {
    name: 'fa-at',
    icon: faAt,
    searchTerms: [
      'at',
      'email',
      'mention',
      'address',
      'آت',
      'بريد',
      'إشارة',
      'عنوان',
    ],
  },
  {
    name: 'fa-inbox',
    icon: faInbox,
    searchTerms: [
      'inbox',
      'mailbox',
      'received',
      'messages',
      'صندوق الوارد',
      'صندوق البريد',
      'مستلم',
      'رسائل',
    ],
  },
  {
    name: 'fa-reply',
    icon: faReply,
    searchTerms: [
      'reply',
      'respond',
      'answer',
      'back',
      'رد',
      'استجابة',
      'إجابة',
      'رجوع',
    ],
  },

  // ===== ALERTS & INFO =====
  {
    name: 'fa-circle-info',
    icon: faCircleInfo,
    searchTerms: [
      'info',
      'information',
      'help',
      'about',
      'details',
      'معلومات',
      'مساعدة',
      'حول',
      'تفاصيل',
    ],
  },
  {
    name: 'fa-circle-question',
    icon: faCircleQuestion,
    searchTerms: [
      'question',
      'help',
      'faq',
      'support',
      'ask',
      'سؤال',
      'مساعدة',
      'أسئلة شائعة',
      'دعم',
      'استفسار',
    ],
  },
  {
    name: 'fa-circle-exclamation',
    icon: faCircleExclamation,
    searchTerms: [
      'exclamation',
      'important',
      'attention',
      'notice',
      'تعجب',
      'مهم',
      'انتباه',
      'ملاحظة',
    ],
  },
  {
    name: 'fa-triangle-exclamation',
    icon: faTriangleExclamation,
    searchTerms: [
      'warning',
      'danger',
      'caution',
      'alert',
      'hazard',
      'تحذير',
      'خطر',
      'حذر',
      'تنبيه',
    ],
  },
  {
    name: 'fa-circle-check',
    icon: faCircleCheck,
    searchTerms: [
      'success',
      'done',
      'complete',
      'approved',
      'verified',
      'نجاح',
      'تم',
      'مكتمل',
      'موافق',
      'موثق',
    ],
  },
  {
    name: 'fa-circle-xmark',
    icon: faCircleXmark,
    searchTerms: [
      'error',
      'failed',
      'cancel',
      'close',
      'reject',
      'خطأ',
      'فشل',
      'إلغاء',
      'إغلاق',
      'رفض',
    ],
  },
  {
    name: 'fa-circle-minus',
    icon: faCircleMinus,
    searchTerms: [
      'minus',
      'remove',
      'subtract',
      'decrease',
      'ناقص',
      'إزالة',
      'طرح',
      'تقليل',
    ],
  },
  {
    name: 'fa-lightbulb',
    icon: faLightbulb,
    searchTerms: [
      'idea',
      'tip',
      'suggestion',
      'hint',
      'innovation',
      'فكرة',
      'نصيحة',
      'اقتراح',
      'تلميح',
      'ابتكار',
    ],
  },
  {
    name: 'fa-bullhorn',
    icon: faBullhorn,
    searchTerms: [
      'announcement',
      'broadcast',
      'megaphone',
      'news',
      'إعلان',
      'بث',
      'مكبر صوت',
      'أخبار',
    ],
  },
  {
    name: 'fa-ban',
    icon: faBan,
    searchTerms: [
      'ban',
      'block',
      'forbidden',
      'prohibited',
      'not allowed',
      'حظر',
      'منع',
      'ممنوع',
      'محظور',
      'غير مسموح',
    ],
  },

  // ===== EDUCATION & LEARNING =====
  {
    name: 'fa-graduation-cap',
    icon: faGraduationCap,
    searchTerms: [
      'graduation',
      'education',
      'academic',
      'degree',
      'university',
      'college',
      'تخرج',
      'تعليم',
      'أكاديمي',
      'درجة',
      'جامعة',
      'كلية',
    ],
  },
  {
    name: 'fa-book',
    icon: faBook,
    searchTerms: [
      'book',
      'read',
      'study',
      'textbook',
      'literature',
      'كتاب',
      'قراءة',
      'دراسة',
      'كتاب دراسي',
      'أدب',
    ],
  },
  {
    name: 'fa-book-open',
    icon: faBookOpen,
    searchTerms: [
      'open book',
      'reading',
      'study',
      'learning',
      'كتاب مفتوح',
      'قراءة',
      'دراسة',
      'تعلم',
    ],
  },
  {
    name: 'fa-book-open-reader',
    icon: faBookOpenReader,
    searchTerms: [
      'reading',
      'study',
      'learning',
      'student',
      'قراءة',
      'دراسة',
      'تعلم',
      'طالب',
    ],
  },
  {
    name: 'fa-books',
    icon: faBooks,
    searchTerms: [
      'books',
      'library',
      'collection',
      'reading',
      'كتب',
      'مكتبة',
      'مجموعة',
      'قراءة',
    ],
  },
  {
    name: 'fa-chalkboard-user',
    icon: faChalkboardUser,
    searchTerms: [
      'classroom',
      'teacher',
      'lesson',
      'teaching',
      'lecture',
      'فصل دراسي',
      'معلم',
      'درس',
      'تدريس',
      'محاضرة',
    ],
  },
  {
    name: 'fa-chalkboard',
    icon: faChalkboard,
    searchTerms: [
      'chalkboard',
      'blackboard',
      'whiteboard',
      'board',
      'سبورة',
      'لوح',
      'لوحة',
    ],
  },
  {
    name: 'fa-pen',
    icon: faPen,
    searchTerms: [
      'pen',
      'write',
      'edit',
      'compose',
      'قلم',
      'كتابة',
      'تعديل',
      'تأليف',
    ],
  },
  {
    name: 'fa-pencil',
    icon: faPencil,
    searchTerms: [
      'pencil',
      'write',
      'draw',
      'sketch',
      'edit',
      'قلم رصاص',
      'كتابة',
      'رسم',
      'تعديل',
    ],
  },
  {
    name: 'fa-school',
    icon: faSchool,
    searchTerms: [
      'school',
      'education',
      'building',
      'academy',
      'institute',
      'مدرسة',
      'تعليم',
      'مبنى',
      'أكاديمية',
      'معهد',
    ],
  },
  {
    name: 'fa-school-flag',
    icon: faSchoolFlag,
    searchTerms: [
      'school flag',
      'education',
      'institution',
      'علم المدرسة',
      'تعليم',
      'مؤسسة',
    ],
  },
  {
    name: 'fa-clipboard',
    icon: faClipboard,
    searchTerms: [
      'clipboard',
      'copy',
      'paste',
      'notes',
      'حافظة',
      'نسخ',
      'لصق',
      'ملاحظات',
    ],
  },
  {
    name: 'fa-clipboard-list',
    icon: faClipboardList,
    searchTerms: [
      'checklist',
      'todo',
      'tasks',
      'list',
      'قائمة مراجعة',
      'مهام',
      'قائمة',
    ],
  },
  {
    name: 'fa-clipboard-check',
    icon: faClipboardCheck,
    searchTerms: [
      'completed',
      'done',
      'finished',
      'checked',
      'مكتمل',
      'تم',
      'منتهي',
      'محدد',
    ],
  },
  {
    name: 'fa-clipboard-question',
    icon: faClipboardQuestion,
    searchTerms: [
      'clipboard question',
      'survey',
      'questionnaire',
      'استبيان',
      'استطلاع',
      'سؤال',
    ],
  },
  {
    name: 'fa-bookmark',
    icon: faBookmark,
    searchTerms: [
      'bookmark',
      'save',
      'favorite',
      'mark',
      'علامة مرجعية',
      'حفظ',
      'مفضلة',
      'علامة',
    ],
  },
  {
    name: 'fa-award',
    icon: faAward,
    searchTerms: [
      'award',
      'prize',
      'achievement',
      'recognition',
      'honor',
      'جائزة',
      'إنجاز',
      'تقدير',
      'شرف',
    ],
  },
  {
    name: 'fa-scroll',
    icon: faScroll,
    searchTerms: [
      'scroll',
      'certificate',
      'diploma',
      'document',
      'لفافة',
      'شهادة',
      'دبلوم',
      'وثيقة',
    ],
  },
  {
    name: 'fa-ruler',
    icon: faRuler,
    searchTerms: [
      'ruler',
      'measure',
      'length',
      'math',
      'مسطرة',
      'قياس',
      'طول',
      'رياضيات',
    ],
  },
  {
    name: 'fa-calculator',
    icon: faCalculator,
    searchTerms: [
      'calculator',
      'math',
      'calculate',
      'numbers',
      'accounting',
      'آلة حاسبة',
      'رياضيات',
      'حساب',
      'أرقام',
      'محاسبة',
    ],
  },
  {
    name: 'fa-flask',
    icon: faFlask,
    searchTerms: [
      'flask',
      'science',
      'chemistry',
      'lab',
      'experiment',
      'قارورة',
      'علوم',
      'كيمياء',
      'مختبر',
      'تجربة',
    ],
  },
  {
    name: 'fa-atom',
    icon: faAtom,
    searchTerms: [
      'atom',
      'science',
      'physics',
      'nuclear',
      'ذرة',
      'علوم',
      'فيزياء',
      'نووي',
    ],
  },
  {
    name: 'fa-dna',
    icon: faDna,
    searchTerms: [
      'dna',
      'biology',
      'genetics',
      'science',
      'حمض نووي',
      'أحياء',
      'وراثة',
      'علوم',
    ],
  },
  {
    name: 'fa-language',
    icon: faLanguage,
    searchTerms: [
      'language',
      'translate',
      'multilingual',
      'speech',
      'لغة',
      'ترجمة',
      'متعدد اللغات',
      'كلام',
    ],
  },
  {
    name: 'fa-spell-check',
    icon: faSpellCheck,
    searchTerms: [
      'spell check',
      'grammar',
      'correct',
      'proofread',
      'تدقيق إملائي',
      'قواعد',
      'تصحيح',
      'مراجعة',
    ],
  },
  {
    name: 'fa-list-check',
    icon: faListCheck,
    searchTerms: [
      'task list',
      'checklist',
      'todo',
      'tasks',
      'قائمة مهام',
      'قائمة مراجعة',
      'مهام',
    ],
  },
  {
    name: 'fa-square-check',
    icon: faSquareCheck,
    searchTerms: [
      'checkbox',
      'checked',
      'done',
      'complete',
      'مربع اختيار',
      'محدد',
      'تم',
      'مكتمل',
    ],
  },
  {
    name: 'fa-backpack',
    icon: faBackpack,
    searchTerms: [
      'backpack',
      'bag',
      'school bag',
      'student',
      'حقيبة ظهر',
      'حقيبة',
      'حقيبة مدرسية',
      'طالب',
    ],
  },
  {
    name: 'fa-apple-whole',
    icon: faAppleWhole,
    searchTerms: [
      'apple',
      'fruit',
      'teacher',
      'education',
      'health',
      'تفاحة',
      'فاكهة',
      'معلم',
      'تعليم',
      'صحة',
    ],
  },

  // ===== TESTS & ASSESSMENTS =====
  {
    name: 'fa-file-circle-question',
    icon: faFileCircleQuestion,
    searchTerms: [
      'test',
      'exam',
      'quiz',
      'assessment',
      'question',
      'اختبار',
      'امتحان',
      'اختبار قصير',
      'تقييم',
      'سؤال',
    ],
  },
  {
    name: 'fa-file-circle-check',
    icon: faFileCircleCheck,
    searchTerms: [
      'test passed',
      'exam success',
      'approved',
      'اختبار ناجح',
      'نجاح الامتحان',
      'موافق عليه',
    ],
  },
  {
    name: 'fa-file-circle-xmark',
    icon: faFileCircleXmark,
    searchTerms: [
      'test failed',
      'exam failed',
      'rejected',
      'اختبار راسب',
      'فشل الامتحان',
      'مرفوض',
    ],
  },
  {
    name: 'fa-list-ol',
    icon: faListOl,
    searchTerms: [
      'numbered list',
      'ordered',
      'steps',
      'sequence',
      'قائمة مرقمة',
      'مرتب',
      'خطوات',
      'تسلسل',
    ],
  },
  {
    name: 'fa-ballot-check',
    icon: faBallotCheck,
    searchTerms: [
      'ballot',
      'vote',
      'election',
      'poll',
      'اقتراع',
      'تصويت',
      'انتخاب',
      'استطلاع',
    ],
  },
  {
    name: 'fa-square-poll-vertical',
    icon: faSquarePollVertical,
    searchTerms: [
      'poll',
      'survey',
      'statistics',
      'results',
      'استطلاع',
      'إحصائيات',
      'نتائج',
    ],
  },
  {
    name: 'fa-square-poll-horizontal',
    icon: faSquarePollHorizontal,
    searchTerms: [
      'poll',
      'survey',
      'chart',
      'results',
      'استطلاع',
      'رسم بياني',
      'نتائج',
    ],
  },
  {
    name: 'fa-percent',
    icon: faPercent,
    searchTerms: [
      'percent',
      'percentage',
      'discount',
      'rate',
      'نسبة مئوية',
      'خصم',
      'معدل',
    ],
  },
  {
    name: 'fa-ranking-star',
    icon: faRankingStar,
    searchTerms: [
      'ranking',
      'leaderboard',
      'top',
      'best',
      'ترتيب',
      'لوحة المتصدرين',
      'أفضل',
      'قمة',
    ],
  },

  // ===== FILES & DOCUMENTS =====
  {
    name: 'fa-file',
    icon: faFile,
    searchTerms: [
      'file',
      'document',
      'page',
      'blank',
      'ملف',
      'وثيقة',
      'صفحة',
      'فارغ',
    ],
  },
  {
    name: 'fa-file-lines',
    icon: faFileLines,
    searchTerms: [
      'document',
      'file',
      'text',
      'content',
      'وثيقة',
      'ملف',
      'نص',
      'محتوى',
    ],
  },
  {
    name: 'fa-file-contract',
    icon: faFileContract,
    searchTerms: [
      'contract',
      'agreement',
      'legal',
      'terms',
      'عقد',
      'اتفاقية',
      'قانوني',
      'شروط',
    ],
  },
  {
    name: 'fa-file-certificate',
    icon: faFileCertificate,
    searchTerms: [
      'certificate',
      'diploma',
      'credential',
      'شهادة',
      'دبلوم',
      'اعتماد',
    ],
  },
  {
    name: 'fa-file-signature',
    icon: faFileSignature,
    searchTerms: [
      'signature',
      'sign',
      'contract',
      'agreement',
      'توقيع',
      'عقد',
      'اتفاقية',
    ],
  },
  {
    name: 'fa-file-invoice',
    icon: faFileInvoice,
    searchTerms: [
      'invoice',
      'bill',
      'receipt',
      'payment',
      'فاتورة',
      'حساب',
      'إيصال',
      'دفع',
    ],
  },
  {
    name: 'fa-file-invoice-dollar',
    icon: faFileInvoiceDollar,
    searchTerms: [
      'invoice',
      'bill',
      'payment',
      'money',
      'فاتورة',
      'حساب',
      'دفع',
      'مال',
    ],
  },
  {
    name: 'fa-folder',
    icon: faFolder,
    searchTerms: [
      'folder',
      'directory',
      'organize',
      'category',
      'مجلد',
      'دليل',
      'تنظيم',
      'فئة',
    ],
  },
  {
    name: 'fa-folder-open',
    icon: faFolderOpen,
    searchTerms: [
      'open folder',
      'directory',
      'browse',
      'مجلد مفتوح',
      'دليل',
      'تصفح',
    ],
  },
  {
    name: 'fa-folder-tree',
    icon: faFolderTree,
    searchTerms: [
      'folder tree',
      'structure',
      'hierarchy',
      'organization',
      'شجرة المجلدات',
      'هيكل',
      'تسلسل',
      'تنظيم',
    ],
  },
  {
    name: 'fa-paperclip',
    icon: faPaperclip,
    searchTerms: [
      'attachment',
      'paperclip',
      'attach',
      'clip',
      'مرفق',
      'مشبك ورق',
      'إرفاق',
    ],
  },
  {
    name: 'fa-file-export',
    icon: faFileExport,
    searchTerms: [
      'export',
      'download',
      'save',
      'output',
      'تصدير',
      'تحميل',
      'حفظ',
      'إخراج',
    ],
  },
  {
    name: 'fa-file-import',
    icon: faFileImport,
    searchTerms: [
      'import',
      'upload',
      'load',
      'input',
      'استيراد',
      'رفع',
      'تحميل',
      'إدخال',
    ],
  },
  {
    name: 'fa-file-pdf',
    icon: faFilePdf,
    searchTerms: [
      'pdf',
      'document',
      'adobe',
      'portable',
      'بي دي إف',
      'وثيقة',
      'أدوبي',
    ],
  },
  {
    name: 'fa-file-word',
    icon: faFileWord,
    searchTerms: [
      'word',
      'document',
      'microsoft',
      'doc',
      'وورد',
      'وثيقة',
      'مايكروسوفت',
    ],
  },
  {
    name: 'fa-file-excel',
    icon: faFileExcel,
    searchTerms: [
      'excel',
      'spreadsheet',
      'microsoft',
      'xls',
      'إكسل',
      'جدول بيانات',
      'مايكروسوفت',
    ],
  },
  {
    name: 'fa-file-powerpoint',
    icon: faFilePowerpoint,
    searchTerms: [
      'powerpoint',
      'presentation',
      'slides',
      'microsoft',
      'باوربوينت',
      'عرض تقديمي',
      'شرائح',
      'مايكروسوفت',
    ],
  },
  {
    name: 'fa-file-image',
    icon: faFileImage,
    searchTerms: [
      'image file',
      'picture',
      'photo',
      'graphic',
      'ملف صورة',
      'صورة',
      'رسم',
    ],
  },
  {
    name: 'fa-file-audio',
    icon: faFileAudio,
    searchTerms: [
      'audio file',
      'music',
      'sound',
      'mp3',
      'ملف صوتي',
      'موسيقى',
      'صوت',
    ],
  },
  {
    name: 'fa-file-video',
    icon: faFileVideo,
    searchTerms: [
      'video file',
      'movie',
      'clip',
      'mp4',
      'ملف فيديو',
      'فيلم',
      'مقطع',
    ],
  },
  {
    name: 'fa-file-zipper',
    icon: faFileZipper,
    searchTerms: [
      'zip',
      'archive',
      'compress',
      'rar',
      'ملف مضغوط',
      'أرشيف',
      'ضغط',
    ],
  },
  {
    name: 'fa-file-plus',
    icon: faFilePlus,
    searchTerms: [
      'add file',
      'new file',
      'create',
      'إضافة ملف',
      'ملف جديد',
      'إنشاء',
    ],
  },
  {
    name: 'fa-file-minus',
    icon: faFileMinus,
    searchTerms: [
      'remove file',
      'delete',
      'subtract',
      'إزالة ملف',
      'حذف',
      'طرح',
    ],
  },
  {
    name: 'fa-file-arrow-up',
    icon: faFileArrowUp,
    searchTerms: ['upload file', 'send', 'submit', 'رفع ملف', 'إرسال', 'تقديم'],
  },
  {
    name: 'fa-file-arrow-down',
    icon: faFileArrowDown,
    searchTerms: ['download file', 'save', 'get', 'تحميل ملف', 'حفظ', 'الحصول'],
  },

  // ===== TIME & CALENDAR =====
  {
    name: 'fa-calendar',
    icon: faCalendar,
    searchTerms: [
      'calendar',
      'date',
      'schedule',
      'event',
      'تقويم',
      'تاريخ',
      'جدول',
      'حدث',
    ],
  },
  {
    name: 'fa-calendar-days',
    icon: faCalendarDays,
    searchTerms: [
      'calendar days',
      'month',
      'dates',
      'أيام التقويم',
      'شهر',
      'تواريخ',
    ],
  },
  {
    name: 'fa-calendar-check',
    icon: faCalendarCheck,
    searchTerms: [
      'calendar check',
      'confirmed',
      'booked',
      'scheduled',
      'تأكيد التقويم',
      'محجوز',
      'مجدول',
    ],
  },
  {
    name: 'fa-calendar-xmark',
    icon: faCalendarXmark,
    searchTerms: [
      'calendar cancel',
      'unavailable',
      'closed',
      'إلغاء التقويم',
      'غير متاح',
      'مغلق',
    ],
  },
  {
    name: 'fa-calendar-plus',
    icon: faCalendarPlus,
    searchTerms: [
      'add event',
      'new date',
      'schedule',
      'إضافة حدث',
      'تاريخ جديد',
      'جدولة',
    ],
  },
  {
    name: 'fa-calendar-minus',
    icon: faCalendarMinus,
    searchTerms: [
      'remove event',
      'cancel',
      'delete date',
      'إزالة حدث',
      'إلغاء',
      'حذف تاريخ',
    ],
  },
  {
    name: 'fa-calendar-clock',
    icon: faCalendarClock,
    searchTerms: [
      'schedule',
      'appointment',
      'time',
      'deadline',
      'جدول',
      'موعد',
      'وقت',
      'موعد نهائي',
    ],
  },
  {
    name: 'fa-calendar-week',
    icon: faCalendarWeek,
    searchTerms: ['week', 'weekly', 'schedule', 'أسبوع', 'أسبوعي', 'جدول'],
  },
  {
    name: 'fa-clock',
    icon: faClock,
    searchTerms: ['clock', 'time', 'hour', 'watch', 'ساعة', 'وقت', 'ساعة يد'],
  },
  {
    name: 'fa-clock-rotate-left',
    icon: faClockRotateLeft,
    searchTerms: [
      'history',
      'undo',
      'past',
      'previous',
      'سجل',
      'تراجع',
      'ماضي',
      'سابق',
    ],
  },
  {
    name: 'fa-hourglass',
    icon: faHourglass,
    searchTerms: [
      'hourglass',
      'waiting',
      'time',
      'loading',
      'ساعة رملية',
      'انتظار',
      'وقت',
      'تحميل',
    ],
  },
  {
    name: 'fa-hourglass-half',
    icon: faHourglassHalf,
    searchTerms: [
      'hourglass half',
      'progress',
      'ongoing',
      'ساعة رملية نصف',
      'تقدم',
      'جاري',
    ],
  },
  {
    name: 'fa-stopwatch',
    icon: faStopwatch,
    searchTerms: [
      'stopwatch',
      'timer',
      'speed',
      'race',
      'ساعة توقيت',
      'مؤقت',
      'سرعة',
      'سباق',
    ],
  },
  {
    name: 'fa-alarm-clock',
    icon: faAlarmClock,
    searchTerms: [
      'alarm',
      'wake up',
      'reminder',
      'alert',
      'منبه',
      'استيقاظ',
      'تذكير',
      'تنبيه',
    ],
  },
  {
    name: 'fa-timer',
    icon: faTimer,
    searchTerms: ['timer', 'countdown', 'duration', 'مؤقت', 'عد تنازلي', 'مدة'],
  },

  // ===== FEEDBACK & RATING =====
  {
    name: 'fa-star',
    icon: faStar,
    searchTerms: [
      'star',
      'favorite',
      'rating',
      'review',
      'best',
      'نجمة',
      'مفضل',
      'تقييم',
      'مراجعة',
      'أفضل',
    ],
  },
  {
    name: 'fa-star-half',
    icon: faStarHalf,
    searchTerms: [
      'half star',
      'rating',
      'partial',
      'نصف نجمة',
      'تقييم',
      'جزئي',
    ],
  },
  {
    name: 'fa-heart',
    icon: faHeart,
    searchTerms: [
      'heart',
      'love',
      'like',
      'favorite',
      'health',
      'قلب',
      'حب',
      'إعجاب',
      'مفضل',
      'صحة',
    ],
  },
  {
    name: 'fa-thumbs-up',
    icon: faThumbsUp,
    searchTerms: [
      'like',
      'approve',
      'good',
      'positive',
      'إعجاب',
      'موافقة',
      'جيد',
      'إيجابي',
    ],
  },
  {
    name: 'fa-thumbs-down',
    icon: faThumbsDown,
    searchTerms: [
      'dislike',
      'disapprove',
      'bad',
      'negative',
      'عدم إعجاب',
      'رفض',
      'سيء',
      'سلبي',
    ],
  },
  {
    name: 'fa-flag',
    icon: faFlag,
    searchTerms: [
      'flag',
      'report',
      'mark',
      'important',
      'علم',
      'بلاغ',
      'علامة',
      'مهم',
    ],
  },
  {
    name: 'fa-flag-checkered',
    icon: faFlagCheckered,
    searchTerms: [
      'finish',
      'complete',
      'race',
      'end',
      'نهاية',
      'إكمال',
      'سباق',
      'انتهاء',
    ],
  },
  {
    name: 'fa-trophy',
    icon: faTrophy,
    searchTerms: [
      'trophy',
      'winner',
      'champion',
      'award',
      'prize',
      'كأس',
      'فائز',
      'بطل',
      'جائزة',
    ],
  },
  {
    name: 'fa-trophy-star',
    icon: faTrophyStar,
    searchTerms: [
      'trophy star',
      'excellence',
      'achievement',
      'كأس نجمة',
      'تميز',
      'إنجاز',
    ],
  },
  {
    name: 'fa-medal',
    icon: faMedal,
    searchTerms: [
      'medal',
      'award',
      'achievement',
      'honor',
      'ميدالية',
      'جائزة',
      'إنجاز',
      'شرف',
    ],
  },
  {
    name: 'fa-crown',
    icon: faCrown,
    searchTerms: [
      'crown',
      'king',
      'queen',
      'royal',
      'premium',
      'تاج',
      'ملك',
      'ملكة',
      'ملكي',
      'مميز',
    ],
  },
  {
    name: 'fa-handshake',
    icon: faHandshake,
    searchTerms: [
      'handshake',
      'agreement',
      'deal',
      'partnership',
      'cooperation',
      'مصافحة',
      'اتفاق',
      'صفقة',
      'شراكة',
      'تعاون',
    ],
  },
  {
    name: 'fa-hands-clapping',
    icon: faHandsClapping,
    searchTerms: [
      'clapping',
      'applause',
      'congratulations',
      'bravo',
      'تصفيق',
      'تهنئة',
      'برافو',
    ],
  },

  // ===== SETTINGS & CONFIG =====
  {
    name: 'fa-gear',
    icon: faGear,
    searchTerms: [
      'settings',
      'gear',
      'config',
      'preferences',
      'options',
      'إعدادات',
      'ترس',
      'تكوين',
      'تفضيلات',
      'خيارات',
    ],
  },
  {
    name: 'fa-gears',
    icon: faGears,
    searchTerms: [
      'settings',
      'configuration',
      'system',
      'multiple',
      'إعدادات',
      'تكوين',
      'نظام',
      'متعدد',
    ],
  },
  {
    name: 'fa-sliders',
    icon: faSliders,
    searchTerms: [
      'sliders',
      'adjust',
      'controls',
      'settings',
      'أشرطة التمرير',
      'ضبط',
      'تحكم',
      'إعدادات',
    ],
  },
  {
    name: 'fa-wrench',
    icon: faWrench,
    searchTerms: [
      'wrench',
      'tool',
      'fix',
      'repair',
      'maintenance',
      'مفتاح ربط',
      'أداة',
      'إصلاح',
      'صيانة',
    ],
  },
  {
    name: 'fa-screwdriver-wrench',
    icon: faScrewdriverWrench,
    searchTerms: [
      'tools',
      'maintenance',
      'repair',
      'fix',
      'أدوات',
      'صيانة',
      'إصلاح',
    ],
  },
  {
    name: 'fa-toggle-on',
    icon: faToggleOn,
    searchTerms: [
      'toggle on',
      'switch',
      'enable',
      'active',
      'تبديل مفعل',
      'مفتاح',
      'تمكين',
      'نشط',
    ],
  },
  {
    name: 'fa-toggle-off',
    icon: faToggleOff,
    searchTerms: [
      'toggle off',
      'switch',
      'disable',
      'inactive',
      'تبديل معطل',
      'مفتاح',
      'تعطيل',
      'غير نشط',
    ],
  },
  {
    name: 'fa-circle-half-stroke',
    icon: faCircleHalfStroke,
    searchTerms: [
      'contrast',
      'theme',
      'dark mode',
      'light mode',
      'تباين',
      'مظهر',
      'الوضع الداكن',
      'الوضع الفاتح',
    ],
  },

  // ===== SECURITY & ACCESS =====
  {
    name: 'fa-lock',
    icon: faLock,
    searchTerms: [
      'lock',
      'secure',
      'private',
      'protected',
      'password',
      'قفل',
      'آمن',
      'خاص',
      'محمي',
      'كلمة مرور',
    ],
  },
  {
    name: 'fa-lock-open',
    icon: faLockOpen,
    searchTerms: [
      'unlock',
      'open',
      'access',
      'public',
      'فتح القفل',
      'مفتوح',
      'وصول',
      'عام',
    ],
  },
  {
    name: 'fa-lock-keyhole',
    icon: faLockKeyhole,
    searchTerms: [
      'lock keyhole',
      'secure',
      'private',
      'قفل ثقب المفتاح',
      'آمن',
      'خاص',
    ],
  },
  {
    name: 'fa-unlock-keyhole',
    icon: faUnlockKeyhole,
    searchTerms: [
      'unlock keyhole',
      'open',
      'access',
      'فتح ثقب المفتاح',
      'مفتوح',
      'وصول',
    ],
  },
  {
    name: 'fa-key',
    icon: faKey,
    searchTerms: [
      'key',
      'password',
      'access',
      'unlock',
      'مفتاح',
      'كلمة مرور',
      'وصول',
      'فتح',
    ],
  },
  {
    name: 'fa-shield',
    icon: faShield,
    searchTerms: [
      'shield',
      'protect',
      'security',
      'defense',
      'درع',
      'حماية',
      'أمان',
      'دفاع',
    ],
  },
  {
    name: 'fa-shield-halved',
    icon: faShieldHalved,
    searchTerms: [
      'security',
      'protection',
      'antivirus',
      'أمان',
      'حماية',
      'مضاد فيروسات',
    ],
  },
  {
    name: 'fa-shield-check',
    icon: faShieldCheck,
    searchTerms: [
      'shield check',
      'verified',
      'secure',
      'protected',
      'درع محقق',
      'موثق',
      'آمن',
      'محمي',
    ],
  },
  {
    name: 'fa-user-shield',
    icon: faUserShield,
    searchTerms: [
      'user shield',
      'protected user',
      'admin',
      'security',
      'مستخدم محمي',
      'مشرف',
      'أمان',
    ],
  },
  {
    name: 'fa-user-lock',
    icon: faUserLock,
    searchTerms: [
      'user lock',
      'blocked',
      'restricted',
      'مستخدم مقفل',
      'محظور',
      'مقيد',
    ],
  },
  {
    name: 'fa-fingerprint',
    icon: faFingerprint,
    searchTerms: [
      'fingerprint',
      'biometric',
      'identity',
      'security',
      'بصمة',
      'بيومتري',
      'هوية',
      'أمان',
    ],
  },
  {
    name: 'fa-eye',
    icon: faEye,
    searchTerms: [
      'eye',
      'view',
      'visible',
      'show',
      'watch',
      'عين',
      'عرض',
      'مرئي',
      'إظهار',
      'مشاهدة',
    ],
  },
  {
    name: 'fa-eye-slash',
    icon: faEyeSlash,
    searchTerms: [
      'eye slash',
      'hide',
      'invisible',
      'private',
      'password',
      'إخفاء',
      'غير مرئي',
      'خاص',
      'كلمة مرور',
    ],
  },

  // ===== PLACES & BUILDINGS =====
  {
    name: 'fa-house',
    icon: faHouse,
    searchTerms: [
      'house',
      'home',
      'residence',
      'dwelling',
      'منزل',
      'بيت',
      'سكن',
      'مسكن',
    ],
  },
  {
    name: 'fa-building',
    icon: faBuilding,
    searchTerms: [
      'building',
      'office',
      'company',
      'corporate',
      'مبنى',
      'مكتب',
      'شركة',
      'مؤسسة',
    ],
  },
  {
    name: 'fa-building-columns',
    icon: faBuildingColumns,
    searchTerms: [
      'institution',
      'bank',
      'government',
      'court',
      'مؤسسة',
      'بنك',
      'حكومة',
      'محكمة',
    ],
  },
  {
    name: 'fa-hospital',
    icon: faHospital,
    searchTerms: [
      'hospital',
      'medical',
      'health',
      'clinic',
      'emergency',
      'مستشفى',
      'طبي',
      'صحة',
      'عيادة',
      'طوارئ',
    ],
  },
  {
    name: 'fa-store',
    icon: faStore,
    searchTerms: [
      'store',
      'shop',
      'retail',
      'market',
      'متجر',
      'محل',
      'تجزئة',
      'سوق',
    ],
  },
  {
    name: 'fa-warehouse',
    icon: faWarehouse,
    searchTerms: [
      'warehouse',
      'storage',
      'inventory',
      'depot',
      'مستودع',
      'تخزين',
      'مخزون',
      'مخزن',
    ],
  },
  {
    name: 'fa-city',
    icon: faCity,
    searchTerms: [
      'city',
      'urban',
      'downtown',
      'skyline',
      'مدينة',
      'حضري',
      'وسط المدينة',
      'أفق',
    ],
  },
  {
    name: 'fa-location-dot',
    icon: faLocationDot,
    searchTerms: [
      'location',
      'pin',
      'map marker',
      'place',
      'موقع',
      'دبوس',
      'علامة خريطة',
      'مكان',
    ],
  },
  {
    name: 'fa-map-location-dot',
    icon: faMapLocationDot,
    searchTerms: [
      'map location',
      'gps',
      'navigate',
      'موقع الخريطة',
      'تحديد المواقع',
      'ملاحة',
    ],
  },
  {
    name: 'fa-map',
    icon: faMap,
    searchTerms: [
      'map',
      'navigation',
      'directions',
      'geography',
      'خريطة',
      'ملاحة',
      'اتجاهات',
      'جغرافيا',
    ],
  },
  {
    name: 'fa-door-open',
    icon: faDoorOpen,
    searchTerms: [
      'door open',
      'entrance',
      'exit',
      'welcome',
      'باب مفتوح',
      'مدخل',
      'مخرج',
      'ترحيب',
    ],
  },
  {
    name: 'fa-door-closed',
    icon: faDoorClosed,
    searchTerms: [
      'door closed',
      'locked',
      'private',
      'باب مغلق',
      'مقفل',
      'خاص',
    ],
  },
  {
    name: 'fa-school-circle-check',
    icon: faSchoolCircleCheck,
    searchTerms: [
      'school approved',
      'verified school',
      'accredited',
      'مدرسة معتمدة',
      'مدرسة موثقة',
    ],
  },

  // ===== FINANCE & PAYMENT =====
  {
    name: 'fa-dollar-sign',
    icon: faDollarSign,
    searchTerms: [
      'dollar',
      'money',
      'currency',
      'price',
      'cost',
      'دولار',
      'مال',
      'عملة',
      'سعر',
      'تكلفة',
    ],
  },
  {
    name: 'fa-money-bill',
    icon: faMoneyBill,
    searchTerms: [
      'money',
      'bill',
      'cash',
      'currency',
      'مال',
      'فاتورة',
      'نقد',
      'عملة',
    ],
  },
  {
    name: 'fa-money-bill-wave',
    icon: faMoneyBillWave,
    searchTerms: [
      'money wave',
      'cash flow',
      'payment',
      'تدفق مالي',
      'دفع',
      'نقد',
    ],
  },
  {
    name: 'fa-money-bills',
    icon: faMoneyBills,
    searchTerms: [
      'money bills',
      'cash',
      'wealth',
      'أوراق نقدية',
      'نقد',
      'ثروة',
    ],
  },
  {
    name: 'fa-money-check',
    icon: faMoneyCheck,
    searchTerms: ['check', 'cheque', 'payment', 'bank', 'شيك', 'دفع', 'بنك'],
  },
  {
    name: 'fa-money-check-dollar',
    icon: faMoneyCheckDollar,
    searchTerms: [
      'check dollar',
      'payment',
      'salary',
      'شيك دولار',
      'دفع',
      'راتب',
    ],
  },
  {
    name: 'fa-money-bill-transfer',
    icon: faMoneyBillTransfer,
    searchTerms: [
      'transfer',
      'send money',
      'transaction',
      'تحويل',
      'إرسال مال',
      'معاملة',
    ],
  },
  {
    name: 'fa-credit-card',
    icon: faCreditCard,
    searchTerms: [
      'credit card',
      'payment',
      'bank card',
      'debit',
      'بطاقة ائتمان',
      'دفع',
      'بطاقة بنكية',
      'بطاقة خصم',
    ],
  },
  {
    name: 'fa-wallet',
    icon: faWallet,
    searchTerms: [
      'wallet',
      'purse',
      'money',
      'payment',
      'محفظة',
      'حقيبة نقود',
      'مال',
      'دفع',
    ],
  },
  {
    name: 'fa-receipt',
    icon: faReceipt,
    searchTerms: [
      'receipt',
      'invoice',
      'bill',
      'transaction',
      'إيصال',
      'فاتورة',
      'حساب',
      'معاملة',
    ],
  },
  {
    name: 'fa-coins',
    icon: faCoins,
    searchTerms: [
      'coins',
      'money',
      'change',
      'currency',
      'عملات معدنية',
      'مال',
      'فكة',
      'عملة',
    ],
  },
  {
    name: 'fa-sack-dollar',
    icon: faSackDollar,
    searchTerms: [
      'money bag',
      'savings',
      'wealth',
      'investment',
      'كيس مال',
      'مدخرات',
      'ثروة',
      'استثمار',
    ],
  },
  {
    name: 'fa-hand-holding-dollar',
    icon: faHandHoldingDollar,
    searchTerms: [
      'payment',
      'donate',
      'give money',
      'charity',
      'دفع',
      'تبرع',
      'إعطاء مال',
      'خيرية',
    ],
  },
  {
    name: 'fa-scale-balanced',
    icon: faScaleBalanced,
    searchTerms: [
      'balance',
      'justice',
      'law',
      'fair',
      'equal',
      'ميزان',
      'عدالة',
      'قانون',
      'عادل',
      'متساوي',
    ],
  },
  {
    name: 'fa-circle-dollar',
    icon: faCircleDollar,
    searchTerms: [
      'dollar circle',
      'money',
      'currency',
      'دائرة دولار',
      'مال',
      'عملة',
    ],
  },
  {
    name: 'fa-badge-check',
    icon: faBadgeCheck,
    searchTerms: [
      'verified',
      'certified',
      'approved',
      'authentic',
      'موثق',
      'معتمد',
      'موافق عليه',
      'أصلي',
    ],
  },

  // ===== CHARTS & ANALYTICS =====
  {
    name: 'fa-chart-line',
    icon: faChartLine,
    searchTerms: [
      'chart',
      'graph',
      'analytics',
      'trend',
      'statistics',
      'رسم بياني',
      'تحليلات',
      'اتجاه',
      'إحصائيات',
    ],
  },
  {
    name: 'fa-chart-line-up',
    icon: faChartLineUp,
    searchTerms: [
      'trend up',
      'growth',
      'increase',
      'positive',
      'اتجاه صاعد',
      'نمو',
      'زيادة',
      'إيجابي',
    ],
  },
  {
    name: 'fa-chart-line-down',
    icon: faChartLineDown,
    searchTerms: [
      'trend down',
      'decline',
      'decrease',
      'negative',
      'اتجاه هابط',
      'انخفاض',
      'تناقص',
      'سلبي',
    ],
  },
  {
    name: 'fa-chart-bar',
    icon: faChartBar,
    searchTerms: [
      'bar chart',
      'graph',
      'statistics',
      'data',
      'رسم بياني شريطي',
      'إحصائيات',
      'بيانات',
    ],
  },
  {
    name: 'fa-chart-pie',
    icon: faChartPie,
    searchTerms: [
      'pie chart',
      'percentage',
      'distribution',
      'رسم بياني دائري',
      'نسبة مئوية',
      'توزيع',
    ],
  },
  {
    name: 'fa-chart-mixed',
    icon: faChartMixed,
    searchTerms: [
      'mixed chart',
      'analytics',
      'comparison',
      'رسم بياني مختلط',
      'تحليلات',
      'مقارنة',
    ],
  },
  {
    name: 'fa-chart-simple',
    icon: faChartSimple,
    searchTerms: [
      'simple chart',
      'basic graph',
      'statistics',
      'رسم بياني بسيط',
      'إحصائيات',
    ],
  },
  {
    name: 'fa-presentation-screen',
    icon: faPresentationScreen,
    searchTerms: [
      'presentation',
      'slides',
      'meeting',
      'display',
      'عرض تقديمي',
      'شرائح',
      'اجتماع',
      'عرض',
    ],
  },
  {
    name: 'fa-gauge',
    icon: faGauge,
    searchTerms: [
      'gauge',
      'meter',
      'dashboard',
      'speed',
      'performance',
      'مقياس',
      'لوحة القيادة',
      'سرعة',
      'أداء',
    ],
  },
  {
    name: 'fa-gauge-high',
    icon: faGaugeHigh,
    searchTerms: [
      'gauge high',
      'fast',
      'performance',
      'speed',
      'مقياس عالي',
      'سريع',
      'أداء',
      'سرعة',
    ],
  },

  // ===== MEDIA & CONTENT =====
  {
    name: 'fa-camera',
    icon: faCamera,
    searchTerms: [
      'camera',
      'photo',
      'picture',
      'capture',
      'كاميرا',
      'صورة',
      'التقاط',
    ],
  },
  {
    name: 'fa-image',
    icon: faImage,
    searchTerms: ['image', 'picture', 'photo', 'graphic', 'صورة', 'رسم'],
  },
  {
    name: 'fa-images',
    icon: faImages,
    searchTerms: [
      'images',
      'gallery',
      'photos',
      'album',
      'صور',
      'معرض',
      'ألبوم',
    ],
  },
  {
    name: 'fa-video',
    icon: faVideo,
    searchTerms: [
      'video',
      'record',
      'movie',
      'film',
      'camera',
      'فيديو',
      'تسجيل',
      'فيلم',
      'كاميرا',
    ],
  },
  {
    name: 'fa-microphone',
    icon: faMicrophone,
    searchTerms: [
      'microphone',
      'audio',
      'record',
      'voice',
      'speak',
      'ميكروفون',
      'صوت',
      'تسجيل',
      'تحدث',
    ],
  },
  {
    name: 'fa-microphone-slash',
    icon: faMicrophoneSlash,
    searchTerms: [
      'mute',
      'microphone off',
      'silent',
      'كتم',
      'ميكروفون مغلق',
      'صامت',
    ],
  },
  {
    name: 'fa-headphones',
    icon: faHeadphones,
    searchTerms: [
      'headphones',
      'audio',
      'music',
      'listen',
      'سماعات',
      'صوت',
      'موسيقى',
      'استماع',
    ],
  },
  {
    name: 'fa-display',
    icon: faDisplay,
    searchTerms: [
      'display',
      'monitor',
      'screen',
      'computer',
      'شاشة',
      'مراقب',
      'كمبيوتر',
    ],
  },
  {
    name: 'fa-desktop',
    icon: faDesktop,
    searchTerms: [
      'desktop',
      'computer',
      'pc',
      'workstation',
      'سطح المكتب',
      'كمبيوتر',
      'حاسوب',
    ],
  },
  {
    name: 'fa-laptop',
    icon: faLaptop,
    searchTerms: [
      'laptop',
      'computer',
      'notebook',
      'portable',
      'لابتوب',
      'كمبيوتر محمول',
      'حاسوب محمول',
    ],
  },
  {
    name: 'fa-mobile',
    icon: faMobile,
    searchTerms: [
      'mobile',
      'phone',
      'smartphone',
      'cell',
      'موبايل',
      'هاتف',
      'جوال',
      'هاتف ذكي',
    ],
  },
  {
    name: 'fa-tablet',
    icon: faTablet,
    searchTerms: ['tablet', 'ipad', 'device', 'تابلت', 'آيباد', 'جهاز لوحي'],
  },
  {
    name: 'fa-screen-users',
    icon: faScreenUsers,
    searchTerms: [
      'virtual class',
      'online meeting',
      'video call',
      'فصل افتراضي',
      'اجتماع عبر الإنترنت',
      'مكالمة فيديو',
    ],
  },
  {
    name: 'fa-webcam',
    icon: faWebcam,
    searchTerms: [
      'webcam',
      'camera',
      'video call',
      'كاميرا ويب',
      'كاميرا',
      'مكالمة فيديو',
    ],
  },
  {
    name: 'fa-photo-film',
    icon: faPhotoFilm,
    searchTerms: [
      'media',
      'photo',
      'film',
      'gallery',
      'وسائط',
      'صورة',
      'فيلم',
      'معرض',
    ],
  },

  // ===== TRANSPORTATION =====
  {
    name: 'fa-bus',
    icon: faBus,
    searchTerms: [
      'bus',
      'transport',
      'public',
      'vehicle',
      'حافلة',
      'نقل',
      'عام',
      'مركبة',
      'باص',
    ],
  },
  {
    name: 'fa-bus-school',
    icon: faBusSchool,
    searchTerms: [
      'school bus',
      'transport',
      'students',
      'حافلة مدرسية',
      'نقل',
      'طلاب',
      'باص المدرسة',
    ],
  },
  {
    name: 'fa-car',
    icon: faCar,
    searchTerms: [
      'car',
      'vehicle',
      'automobile',
      'drive',
      'سيارة',
      'مركبة',
      'قيادة',
    ],
  },
  {
    name: 'fa-route',
    icon: faRoute,
    searchTerms: [
      'route',
      'path',
      'direction',
      'journey',
      'مسار',
      'طريق',
      'اتجاه',
      'رحلة',
    ],
  },
  {
    name: 'fa-road',
    icon: faRoad,
    searchTerms: [
      'road',
      'street',
      'highway',
      'path',
      'طريق',
      'شارع',
      'طريق سريع',
      'مسار',
    ],
  },
  {
    name: 'fa-location-crosshairs',
    icon: faLocationCrosshairs,
    searchTerms: [
      'current location',
      'gps',
      'target',
      'الموقع الحالي',
      'تحديد المواقع',
      'هدف',
    ],
  },
  {
    name: 'fa-compass',
    icon: faCompass,
    searchTerms: [
      'compass',
      'direction',
      'navigation',
      'explore',
      'بوصلة',
      'اتجاه',
      'ملاحة',
      'استكشاف',
    ],
  },

  // ===== MAINTENANCE & ENVIRONMENT =====
  {
    name: 'fa-broom',
    icon: faBroom,
    searchTerms: [
      'broom',
      'clean',
      'sweep',
      'housekeeping',
      'مكنسة',
      'تنظيف',
      'كنس',
      'تدبير منزلي',
    ],
  },
  {
    name: 'fa-spray-can-sparkles',
    icon: faSprayCanSparkles,
    searchTerms: [
      'sanitize',
      'clean',
      'spray',
      'disinfect',
      'تعقيم',
      'تنظيف',
      'رش',
      'تطهير',
    ],
  },
  {
    name: 'fa-trash-can',
    icon: faTrashCan,
    searchTerms: [
      'trash',
      'delete',
      'remove',
      'garbage',
      'bin',
      'سلة مهملات',
      'حذف',
      'إزالة',
      'قمامة',
    ],
  },
  {
    name: 'fa-recycle',
    icon: faRecycle,
    searchTerms: [
      'recycle',
      'environment',
      'green',
      'eco',
      'إعادة تدوير',
      'بيئة',
      'أخضر',
      'صديق للبيئة',
    ],
  },
  {
    name: 'fa-leaf',
    icon: faLeaf,
    searchTerms: [
      'leaf',
      'nature',
      'eco',
      'green',
      'environment',
      'ورقة شجر',
      'طبيعة',
      'بيئة',
      'أخضر',
    ],
  },
  {
    name: 'fa-tree',
    icon: faTree,
    searchTerms: [
      'tree',
      'nature',
      'forest',
      'park',
      'environment',
      'شجرة',
      'طبيعة',
      'غابة',
      'حديقة',
      'بيئة',
    ],
  },
  {
    name: 'fa-seedling',
    icon: faSeedling,
    searchTerms: [
      'seedling',
      'plant',
      'grow',
      'nature',
      'شتلة',
      'نبات',
      'نمو',
      'طبيعة',
    ],
  },
  {
    name: 'fa-droplet',
    icon: faDroplet,
    searchTerms: ['water', 'drop', 'liquid', 'fluid', 'ماء', 'قطرة', 'سائل'],
  },
  {
    name: 'fa-fan',
    icon: faFan,
    searchTerms: [
      'fan',
      'cooling',
      'air',
      'ventilation',
      'مروحة',
      'تبريد',
      'هواء',
      'تهوية',
    ],
  },
  {
    name: 'fa-temperature-half',
    icon: faTemperatureHalf,
    searchTerms: [
      'temperature',
      'thermometer',
      'weather',
      'heat',
      'درجة الحرارة',
      'مقياس حرارة',
      'طقس',
      'حرارة',
    ],
  },
  {
    name: 'fa-plug',
    icon: faPlug,
    searchTerms: [
      'plug',
      'electric',
      'power',
      'socket',
      'قابس',
      'كهرباء',
      'طاقة',
      'مقبس',
    ],
  },
  {
    name: 'fa-toolbox',
    icon: faToolbox,
    searchTerms: [
      'toolbox',
      'tools',
      'repair',
      'maintenance',
      'صندوق أدوات',
      'أدوات',
      'إصلاح',
      'صيانة',
    ],
  },
  {
    name: 'fa-hammer',
    icon: faHammer,
    searchTerms: [
      'hammer',
      'tool',
      'build',
      'construction',
      'مطرقة',
      'أداة',
      'بناء',
      'تشييد',
    ],
  },

  // ===== FOOD & CANTEEN =====
  {
    name: 'fa-utensils',
    icon: faUtensils,
    searchTerms: [
      'utensils',
      'food',
      'restaurant',
      'eat',
      'dining',
      'أدوات طعام',
      'طعام',
      'مطعم',
      'أكل',
      'تناول الطعام',
    ],
  },
  {
    name: 'fa-bowl-food',
    icon: faBowlFood,
    searchTerms: [
      'bowl',
      'food',
      'meal',
      'soup',
      'وعاء',
      'طعام',
      'وجبة',
      'شوربة',
    ],
  },
  {
    name: 'fa-mug-hot',
    icon: faMugHot,
    searchTerms: [
      'mug',
      'coffee',
      'tea',
      'hot drink',
      'beverage',
      'كوب',
      'قهوة',
      'شاي',
      'مشروب ساخن',
    ],
  },
  {
    name: 'fa-glass-water',
    icon: faGlassWater,
    searchTerms: [
      'water',
      'glass',
      'drink',
      'beverage',
      'ماء',
      'كأس',
      'شراب',
      'مشروب',
    ],
  },
  {
    name: 'fa-cookie',
    icon: faCookie,
    searchTerms: [
      'cookie',
      'snack',
      'biscuit',
      'treat',
      'كعكة',
      'وجبة خفيفة',
      'بسكويت',
      'حلوى',
    ],
  },
  {
    name: 'fa-carrot',
    icon: faCarrot,
    searchTerms: [
      'carrot',
      'vegetable',
      'healthy',
      'food',
      'جزر',
      'خضار',
      'صحي',
      'طعام',
    ],
  },

  // ===== CLOTHING & UNIFORM =====
  {
    name: 'fa-shirt',
    icon: faShirt,
    searchTerms: [
      'shirt',
      'clothing',
      'uniform',
      'dress',
      'قميص',
      'ملابس',
      'زي',
      'لباس',
    ],
  },
  {
    name: 'fa-vest',
    icon: faVest,
    searchTerms: [
      'vest',
      'jacket',
      'uniform',
      'safety',
      'سترة',
      'جاكيت',
      'زي',
      'سلامة',
    ],
  },
  {
    name: 'fa-shoe-prints',
    icon: faShoePrints,
    searchTerms: [
      'shoes',
      'footwear',
      'footsteps',
      'walk',
      'أحذية',
      'حذاء',
      'آثار أقدام',
      'مشي',
    ],
  },
  {
    name: 'fa-socks',
    icon: faSocks,
    searchTerms: ['socks', 'clothing', 'feet', 'جوارب', 'ملابس', 'أقدام'],
  },

  // ===== HELP & SUPPORT =====
  {
    name: 'fa-life-ring',
    icon: faLifeRing,
    searchTerms: [
      'life ring',
      'help',
      'support',
      'rescue',
      'safety',
      'طوق نجاة',
      'مساعدة',
      'دعم',
      'إنقاذ',
      'سلامة',
    ],
  },
  {
    name: 'fa-headset',
    icon: faHeadset,
    searchTerms: [
      'headset',
      'support',
      'customer service',
      'call center',
      'سماعة رأس',
      'دعم',
      'خدمة عملاء',
      'مركز اتصال',
    ],
  },
  {
    name: 'fa-handshake-angle',
    icon: faHandshakeAngle,
    searchTerms: [
      'helping hand',
      'support',
      'assistance',
      'charity',
      'يد المساعدة',
      'دعم',
      'مساعدة',
      'خيرية',
    ],
  },
  {
    name: 'fa-hand-holding-heart',
    icon: faHandHoldingHeart,
    searchTerms: [
      'care',
      'charity',
      'donate',
      'love',
      'support',
      'رعاية',
      'خيرية',
      'تبرع',
      'حب',
      'دعم',
    ],
  },
  {
    name: 'fa-certificate',
    icon: faCertificate,
    searchTerms: [
      'certificate',
      'badge',
      'award',
      'achievement',
      'شهادة',
      'شارة',
      'جائزة',
      'إنجاز',
    ],
  },

  // ===== ACCESSIBILITY =====
  {
    name: 'fa-universal-access',
    icon: faUniversalAccess,
    searchTerms: [
      'accessibility',
      'universal',
      'disability',
      'inclusive',
      'إمكانية الوصول',
      'عالمي',
      'إعاقة',
      'شامل',
    ],
  },
  {
    name: 'fa-wheelchair',
    icon: faWheelchair,
    searchTerms: [
      'wheelchair',
      'disability',
      'accessible',
      'mobility',
      'كرسي متحرك',
      'إعاقة',
      'متاح',
      'حركة',
    ],
  },
  {
    name: 'fa-ear-listen',
    icon: faEarListen,
    searchTerms: [
      'hearing',
      'listen',
      'audio',
      'ear',
      'سمع',
      'استماع',
      'صوت',
      'أذن',
    ],
  },
  {
    name: 'fa-ear-deaf',
    icon: faEarDeaf,
    searchTerms: ['deaf', 'hearing impaired', 'أصم', 'ضعف السمع'],
  },
  {
    name: 'fa-hands-asl-interpreting',
    icon: faHandsAslInterpreting,
    searchTerms: [
      'sign language',
      'asl',
      'deaf',
      'communication',
      'لغة الإشارة',
      'أصم',
      'تواصل',
    ],
  },
  {
    name: 'fa-braille',
    icon: faBraille,
    searchTerms: [
      'braille',
      'blind',
      'visually impaired',
      'بريل',
      'أعمى',
      'ضعف البصر',
    ],
  },

  // ===== STRUCTURE & ORGANIZATION =====
  {
    name: 'fa-sitemap',
    icon: faSitemap,
    searchTerms: [
      'sitemap',
      'structure',
      'hierarchy',
      'organization',
      'خريطة الموقع',
      'هيكل',
      'تسلسل',
      'تنظيم',
    ],
  },
  {
    name: 'fa-diagram-project',
    icon: faDiagramProject,
    searchTerms: [
      'project',
      'diagram',
      'workflow',
      'process',
      'مشروع',
      'مخطط',
      'سير العمل',
      'عملية',
    ],
  },
  {
    name: 'fa-list-tree',
    icon: faListTree,
    searchTerms: [
      'tree list',
      'hierarchy',
      'structure',
      'nested',
      'قائمة شجرية',
      'تسلسل',
      'هيكل',
      'متداخل',
    ],
  },
  {
    name: 'fa-layer-group',
    icon: faLayerGroup,
    searchTerms: [
      'layers',
      'stack',
      'group',
      'levels',
      'طبقات',
      'مكدس',
      'مجموعة',
      'مستويات',
    ],
  },
  {
    name: 'fa-object-group',
    icon: faObjectGroup,
    searchTerms: [
      'group',
      'objects',
      'combine',
      'merge',
      'مجموعة',
      'كائنات',
      'دمج',
      'جمع',
    ],
  },
  {
    name: 'fa-table-cells',
    icon: faTableCells,
    searchTerms: [
      'table',
      'grid',
      'cells',
      'spreadsheet',
      'جدول',
      'شبكة',
      'خلايا',
    ],
  },
  {
    name: 'fa-table-list',
    icon: faTableList,
    searchTerms: [
      'table list',
      'data',
      'records',
      'قائمة جدول',
      'بيانات',
      'سجلات',
    ],
  },
  {
    name: 'fa-grid',
    icon: faGrid,
    searchTerms: [
      'grid',
      'layout',
      'tiles',
      'gallery',
      'شبكة',
      'تخطيط',
      'بلاط',
      'معرض',
    ],
  },

  // ===== ROLES & PERMISSIONS =====
  {
    name: 'fa-user-tag',
    icon: faUserTag,
    searchTerms: [
      'user tag',
      'role',
      'label',
      'category',
      'علامة مستخدم',
      'دور',
      'تصنيف',
      'فئة',
    ],
  },
  {
    name: 'fa-users-between-lines',
    icon: faUsersBetweenLines,
    searchTerms: [
      'users list',
      'members',
      'team',
      'قائمة مستخدمين',
      'أعضاء',
      'فريق',
    ],
  },
  {
    name: 'fa-users-rectangle',
    icon: faUsersRectangle,
    searchTerms: [
      'users group',
      'team',
      'organization',
      'مجموعة مستخدمين',
      'فريق',
      'منظمة',
    ],
  },
  {
    name: 'fa-user-secret',
    icon: faUserSecret,
    searchTerms: [
      'admin',
      'secret',
      'spy',
      'anonymous',
      'مشرف',
      'سري',
      'جاسوس',
      'مجهول',
    ],
  },
  {
    name: 'fa-book-open-cover',
    icon: faBookOpenCover,
    searchTerms: [
      'course',
      'curriculum',
      'syllabus',
      'program',
      'مقرر',
      'منهج',
      'برنامج',
    ],
  },
  {
    name: 'fa-box-archive',
    icon: faBoxArchive,
    searchTerms: [
      'archive',
      'storage',
      'backup',
      'old',
      'أرشيف',
      'تخزين',
      'نسخ احتياطي',
      'قديم',
    ],
  },

  // ===== ANNOUNCEMENTS & NOTIFICATIONS =====
  {
    name: 'fa-newspaper',
    icon: faNewspaper,
    searchTerms: [
      'newspaper',
      'news',
      'article',
      'press',
      'صحيفة',
      'أخبار',
      'مقال',
      'صحافة',
    ],
  },
  {
    name: 'fa-rss',
    icon: faRss,
    searchTerms: [
      'rss',
      'feed',
      'subscribe',
      'updates',
      'تغذية',
      'اشتراك',
      'تحديثات',
    ],
  },
  {
    name: 'fa-tower-broadcast',
    icon: faTowerBroadcast,
    searchTerms: [
      'broadcast',
      'tower',
      'signal',
      'transmission',
      'بث',
      'برج',
      'إشارة',
      'إرسال',
    ],
  },
  {
    name: 'fa-satellite-dish',
    icon: faSatelliteDish,
    searchTerms: [
      'satellite',
      'dish',
      'signal',
      'communication',
      'قمر صناعي',
      'طبق',
      'إشارة',
      'اتصال',
    ],
  },

  // ===== SEARCH & FILTER =====
  {
    name: 'fa-magnifying-glass',
    icon: faMagnifyingGlass,
    searchTerms: [
      'search',
      'find',
      'lookup',
      'magnify',
      'بحث',
      'إيجاد',
      'عدسة مكبرة',
    ],
  },
  {
    name: 'fa-magnifying-glass-plus',
    icon: faMagnifyingGlassPlus,
    searchTerms: ['zoom in', 'magnify', 'enlarge', 'تكبير', 'تضخيم', 'توسيع'],
  },
  {
    name: 'fa-magnifying-glass-minus',
    icon: faMagnifyingGlassMinus,
    searchTerms: ['zoom out', 'reduce', 'shrink', 'تصغير', 'تقليل'],
  },
  {
    name: 'fa-filter',
    icon: faFilter,
    searchTerms: [
      'filter',
      'sort',
      'refine',
      'narrow',
      'فلتر',
      'تصفية',
      'ترتيب',
      'تنقية',
    ],
  },
  {
    name: 'fa-sort',
    icon: faSort,
    searchTerms: [
      'sort',
      'order',
      'arrange',
      'organize',
      'ترتيب',
      'تنظيم',
      'ترتيب',
    ],
  },

  // ===== ACTIONS =====
  {
    name: 'fa-plus',
    icon: faPlus,
    searchTerms: [
      'add',
      'plus',
      'new',
      'create',
      'إضافة',
      'زائد',
      'جديد',
      'إنشاء',
    ],
  },
  {
    name: 'fa-minus',
    icon: faMinus,
    searchTerms: [
      'minus',
      'remove',
      'subtract',
      'decrease',
      'ناقص',
      'إزالة',
      'طرح',
      'تقليل',
    ],
  },
  {
    name: 'fa-check',
    icon: faCheck,
    searchTerms: [
      'check',
      'done',
      'complete',
      'confirm',
      'yes',
      'تحقق',
      'تم',
      'مكتمل',
      'تأكيد',
      'نعم',
    ],
  },
  {
    name: 'fa-xmark',
    icon: faXmark,
    searchTerms: [
      'close',
      'cancel',
      'remove',
      'delete',
      'no',
      'إغلاق',
      'إلغاء',
      'إزالة',
      'حذف',
      'لا',
    ],
  },
  {
    name: 'fa-pen-to-square',
    icon: faPenToSquare,
    searchTerms: [
      'edit',
      'modify',
      'update',
      'change',
      'تعديل',
      'تحديث',
      'تغيير',
    ],
  },
  {
    name: 'fa-trash',
    icon: faTrash,
    searchTerms: [
      'delete',
      'remove',
      'trash',
      'discard',
      'حذف',
      'إزالة',
      'سلة مهملات',
      'تخلص',
    ],
  },
  {
    name: 'fa-download',
    icon: faDownload,
    searchTerms: [
      'download',
      'save',
      'get',
      'export',
      'تحميل',
      'حفظ',
      'الحصول',
      'تصدير',
    ],
  },
  {
    name: 'fa-upload',
    icon: faUpload,
    searchTerms: [
      'upload',
      'send',
      'submit',
      'import',
      'رفع',
      'إرسال',
      'تقديم',
      'استيراد',
    ],
  },
  {
    name: 'fa-share',
    icon: faShare,
    searchTerms: [
      'share',
      'send',
      'forward',
      'distribute',
      'مشاركة',
      'إرسال',
      'توزيع',
    ],
  },
  {
    name: 'fa-share-nodes',
    icon: faShareNodes,
    searchTerms: [
      'share network',
      'social',
      'distribute',
      'شبكة مشاركة',
      'اجتماعي',
      'توزيع',
    ],
  },
  {
    name: 'fa-print',
    icon: faPrint,
    searchTerms: [
      'print',
      'printer',
      'paper',
      'output',
      'طباعة',
      'طابعة',
      'ورق',
      'إخراج',
    ],
  },
  {
    name: 'fa-copy',
    icon: faCopy,
    searchTerms: ['copy', 'duplicate', 'clone', 'نسخ', 'تكرار', 'استنساخ'],
  },
  {
    name: 'fa-link',
    icon: faLink,
    searchTerms: ['link', 'url', 'chain', 'connect', 'رابط', 'سلسلة', 'اتصال'],
  },
  {
    name: 'fa-link-slash',
    icon: faLinkSlash,
    searchTerms: ['unlink', 'disconnect', 'break', 'فك الارتباط', 'فصل', 'قطع'],
  },
  {
    name: 'fa-rotate',
    icon: faRotate,
    searchTerms: [
      'rotate',
      'refresh',
      'reload',
      'sync',
      'تدوير',
      'تحديث',
      'إعادة تحميل',
      'مزامنة',
    ],
  },
  {
    name: 'fa-arrows-rotate',
    icon: faArrowsRotate,
    searchTerms: [
      'refresh',
      'reload',
      'sync',
      'update',
      'تحديث',
      'إعادة تحميل',
      'مزامنة',
    ],
  },
  {
    name: 'fa-right-from-bracket',
    icon: faRightFromBracket,
    searchTerms: [
      'logout',
      'sign out',
      'exit',
      'leave',
      'تسجيل خروج',
      'خروج',
      'مغادرة',
    ],
  },
  {
    name: 'fa-right-to-bracket',
    icon: faRightToBracket,
    searchTerms: [
      'login',
      'sign in',
      'enter',
      'access',
      'تسجيل دخول',
      'دخول',
      'وصول',
    ],
  },
  {
    name: 'fa-expand',
    icon: faExpand,
    searchTerms: [
      'expand',
      'fullscreen',
      'maximize',
      'enlarge',
      'توسيع',
      'ملء الشاشة',
      'تكبير',
    ],
  },
  {
    name: 'fa-compress',
    icon: faCompress,
    searchTerms: [
      'compress',
      'minimize',
      'shrink',
      'reduce',
      'ضغط',
      'تصغير',
      'تقليل',
    ],
  },
];

// Lookup map: icon name string -> IconDefinition
export const ICON_NAME_TO_DEFINITION: Record<string, IconDefinition> =
  ICON_CHOOSER_OPTIONS.reduce(
    (acc, opt) => {
      acc[opt.name] = opt.icon;
      return acc;
    },
    {} as Record<string, IconDefinition>,
  );
