import { IPaginatedResponse, IPaginationParams } from '@shared/interfaces';
import { RESOURCE_PERMISSION } from '@shared/role-bace-acces-controller/resource-permission.constant';

export enum ReportType {
  ATTENDANCE_SUMMARY_AT_SCHOOL_LEVEL = 'ATTENDANCE_SUMMARY_AT_SCHOOL_LEVEL',
  DAILY_ATTENDANCE_AT_LEVEL_LEVEL = 'DAILY_ATTENDANCE_AT_LEVEL_LEVEL',
  ATTENDANCE_SUMMARY_AT_STUDENT_LEVEL = 'ATTENDANCE_SUMMARY_AT_STUDENT_LEVEL',
  ACTIVATION_AT_STUDENT_LEVEL = 'ACTIVATION_AT_STUDENT_LEVEL',
  ACTIVATION_AT_EMPLOYEE_LEVEL = 'ACTIVATION_AT_EMPLOYEE_LEVEL',
  ACTIVATION_AT_GUARDIAN_LEVEL = 'ACTIVATION_AT_GUARDIAN_LEVEL',
  USERS_ACTIVATION_AT_SCHOOL_LEVEL = 'USERS_ACTIVATION_AT_SCHOOL_LEVEL',
  CONTENT_INTERACTION_AT_SCHOOL_LEVEL = 'CONTENT_INTERACTION_AT_SCHOOL_LEVEL',
  COMMUNICATIONS_AT_SCHOOL_LEVEL = 'COMMUNICATIONS_AT_SCHOOL_LEVEL',
  INTERACTION_WITH_CONTENT_AT_TEACHER_LEVEL = 'INTERACTION_WITH_CONTENT_AT_TEACHER_LEVEL',
  INTERACTION_WITH_CONTENT_AT_STAFF_LEVEL = 'INTERACTION_WITH_CONTENT_AT_STAFF_LEVEL',
  SUPPORT_TICKETS_AT_SCHOOL_LEVEL = 'SUPPORT_TICKETS_AT_SCHOOL_LEVEL',
  SMS_AT_CLASS_LEVEL = 'SMS_AT_CLASS_LEVEL',
  PICKUP_AT_CLASS_LEVEL = 'PICKUP_AT_CLASS_LEVEL',
  STUDENT_GUARDIAN_REPORT_AT_CLASS_LEVEL = 'STUDENT_GUARDIAN_REPORT_AT_CLASS_LEVEL',
}
export const ReportTypePermission: { [key in ReportType]: number } = {
  ATTENDANCE_SUMMARY_AT_SCHOOL_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.Attendance_Summary_At_School_Level,
  DAILY_ATTENDANCE_AT_LEVEL_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.Daily_Attendance_At_Level_Level,
  ATTENDANCE_SUMMARY_AT_STUDENT_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.Attendance_Summary_At_Student_Level,
  ACTIVATION_AT_STUDENT_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.ACTIVATION_AT_STUDENT_LEVEL,
  ACTIVATION_AT_EMPLOYEE_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.ACTIVATION_AT_EMPLOYEE_LEVEL,
  ACTIVATION_AT_GUARDIAN_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.ACTIVATION_AT_GUARDIAN_LEVEL,
  USERS_ACTIVATION_AT_SCHOOL_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.USERS_ACTIVATION_AT_SCHOOL_LEVEL,
  CONTENT_INTERACTION_AT_SCHOOL_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.CONTENT_INTERACTION_AT_SCHOOL_LEVEL,
  COMMUNICATIONS_AT_SCHOOL_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.COMMUNICATIONS_AT_SCHOOL_LEVEL,
  INTERACTION_WITH_CONTENT_AT_TEACHER_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ
      .INTERACTION_COMMUNICATIONS_AT_TEACHER_LEVEL,
  SUPPORT_TICKETS_AT_SCHOOL_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.SUPPORT_TICKETS_AT_SCHOOL_LEVEL,
  SMS_AT_CLASS_LEVEL: RESOURCE_PERMISSION.REPORTS.READ.SMS_AT_CLASS_LEVEL,
  PICKUP_AT_CLASS_LEVEL: RESOURCE_PERMISSION.REPORTS.READ.PICKUP_AT_CLASS_LEVEL,
  STUDENT_GUARDIAN_REPORT_AT_CLASS_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ.STUDENT_GUARDIAN_REPORT_AT_CLASS_LEVEL,
  INTERACTION_WITH_CONTENT_AT_STAFF_LEVEL:
    RESOURCE_PERMISSION.REPORTS.READ
      .INTERACTION_AND_COMMUNICATION_AT_STAFF_LEVEL,
};

export enum ReportGenerationStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}

export interface ReportTarget {
  name: string;
  type: string;
  entityId: number;
}

export interface ReportParams {
  dateFrom: string;
  dateTo: string;
  targets: ReportTarget[];
}

export interface ReportItemDTO {
  id: number;
  //tenantId: number;
  reportType: ReportType;
  reportStatus: ReportGenerationStatus;
  //language: string;
  key: string;
  reason: string | null;
  params: Record<string, any>;
  //startedAt: string;
  completedAt: string;
  messageRef: string | null;
  createdAt: string;
}

export type ReportParamsDTO = {
  dateFrom?: string;
  dateTo?: string;
  reportType?: ReportType[];
  status?: ReportGenerationStatus[];
} & IPaginationParams;

export type ReportResponseDTO = IPaginatedResponse<ReportItemDTO[]>;
